export const clones = [
    {
        id: 1,
        imgSrc: 'images/clones//Rex.jpg',
        name: 'Rex',
        CID: 'CT_7567',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: ["501st Legion", "Rishi Station Unit"],
        homeworld: 'Kamino',
        birth: '32 BBY, Kamino',
        rank: ["Captain", "Commander", "ARC Trooper"],
        weapons: 'Twin DC-17s pistol blasters',
        tags: ["Captain", "Commander", "ARC Trooper", "501st Legion", "Rishi Station Unit", "Clone Wars", "Order 66", "Rebel Alliance"]
    },
    {
        id: 2, 
        imgSrc: 'images/clones//Cody.jpg',
        name: 'Cody',
        CID: 'CC-2224',
        species: 'Human',
        gender: 'Male',
        legion: 'Attack_Battalion_212',
        legions: ["212th Attack Battalion", "7th SKy Corps", "Rishi Station Unit", "Crosshair and Cody's Team"],
        homeworld: 'Kamino',
        birth: '32 BBY, Kamino',
        rank: 'Marshal Commander',
        weapons: 'DC-15A Blaster Rifle',
        tags: ["Commander", "212th Attack Battalion", "Third Systems Army", "7th Sky Corps", "Rishi Station Unit", "Crosshair and Cody's Team", "Clone Wars", "Galactic Empire"]
    },
    {
        id: 3,
        imgSrc: 'images/clones//Fives.jpg',
        name: 'Fives',
        CID: 'CT-5555',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: ["501st Legion", "Domino Squad", "Rishi Station Unit"],
        homeworld: 'Kamino',
        death: '19 BBY, Coruscant',
        rank: 'ARC Trooper',
        weapon: 'DC-15A Blaster Rifle',
        tags: ["ARC Trooper", "501st Legion", "Domino Squad", "Rishi Station Unit", "Clone Wars"]
    },
    {
        id: 4,
        imgSrc: 'images/clones//Echo.jpg',
        name: 'Echo',
        name2: 'Hero of Annexes',
        CID: 'CT-1409',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: ["501st Legion", "Clone Force 99"],
        homeworld: 'Kamino',
        birth: 'Kamino',
        rank: ["Clone Corporal", "ARC Trooper"],
        weapon: 'DC-17 Hand Blasters',
        tags: ["ARC Trooper", "Clone Corporal", "Domino Squad", "Rishi Station Unit", "501st Legion", "Clone Force 99", "Clone Wars"]
    },
    {
        id: 5,
        imgSrc: 'images/clones//Gregor.jpg',
        name: 'Gregor',
        CID: 'CC-5576',
        species: 'Human',
        gender: 'Male',
        legion: 'Attack_Battalion_212',
        legions: ["212th Attack Battalion", "Foxtrot Group", "D-Squad"],
        homeworld: 'Kamino',
        birth: '32 BBY, Kamino',
        death: '1 BBY, Lothal',
        rank: ["Captain", "Commander"],
        weapon: 'DC-17m Interchangeable Weapon System',
        tags: ["Captain", "Commander", "212th Attack Battalion", "Foxtrot Group", "D-Squad", "Clone Wars", "Rebel Alliance", "Phoenix Cell"] 
    },
    {
        id: 6, 
        imgSrc: 'images/clones//Wolffe.jpg',
        name: 'Wolffe',
        CID: "CC-3636",
        species: 'Human',
        gender: 'Male',
        legion: 'Battalion_104',
        legions: ["104th Battalion", "Recovery Strike Team", "Phoenix Cell"],
        homeworld: 'Kamino',
        birth: '32 BBY, Kamino',
        rank: 'Commander',
        tags: ["Commander", "104th Battalion", "Clone Wars", "Galactic Empire", "Recovery Strike Team", "Rebel Alliance", "Phoenix Cell"]
    },
    {
        id: 7,
        imgSrc: 'images/clones//Kix.jpg',
        name: 'Kix',
        CID: 'CT-6116',
        legion: "Legion_501",
        legions: ["501st Legion", "Republic Medic Corps"],
        homeworld: 'Kamino',
        rank: 'Medic',
        weapon: 'DC-17 Hand Blasters',
        tags: ["Medic", "501st Legion", "Republic Medic Corps", "Clone Wars"]
    },
    {
        id: 8,
        imgSrc: 'images/clones//Jesse.jpg',
        name: 'Jesse',
        CID: 'CT-6116',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: '501st Legion',
        homeworld: 'Kamino',
        death: '19 BBY, Tribunal',
        rank: ["ARC Trooper", "Lieutenant"],
        weapons: ["DC-15A Blaster Carbine", "DC-17 Hand Blasters"],
        tags: ["ARC Trooper", "Lieutenant", "501st Legion", "Clone Wars"]
    },
    {
        id: 9,
        imgSrc: 'images/clones//99.jpg',
        name: '99',
        homeworld: 'Kamino',
        death: '21 BBY, Kamino',
        tags: ["Clone Wars"]
    },
    {
        id: 10,
        imgSrc: 'images/clones//Hunter.jpg',
        name: 'Hunter',
        CID: 'CT-9901',
        species: 'Human',
        gender: 'Male',
        legion: 'Bad_Batch',
        legions: 'Clone Force 99',
        homeworld: 'Kamino',
        rank: 'Commando',
        weapons: ["DC-17 Hand Blaster", "DC-17m Interchangeable Weapon System", "Vibro-knife sheath"],
        tags: ["Sergeant", "Clone Force 99", "Clone Wars"]

    },
    {
        id: 11,
        imgSrc: 'images/clones//Crosshair.jpg',
        name: 'Crosshair',
        CID: 'CT-9904',
        species: 'Human',
        gender: 'Male',
        legion: 'Bad_Batch',
        legions: 'Clone Force 99',
        homeworld: 'Kamino',
        rank: 'Commando',
        weapons: ["773 Firepuncher Sniper Rifle", "DC-17 Hand Blaster"],
        tags: ["Commando", "Clone Force 99", "Elite Squad", "Crosshair and Cody's Team", "Clone Wars", "Galactic Empire"]
    },
    {
        id: 12,
        imgSrc: 'images/clones//Tech.jpg',
        name: 'Tech',
        CID: 'CT-9902',
        species: 'Human',
        gender: 'Male',
        legion: 'Bad_Batch',
        legions: 'Clone Force 99',
        homeworld: 'Kamino',
        death: '18 BBY, Eriadu',
        rank: 'Commando',
        weapons: ["DC-17 Hand Blasters", "DC-15A Blaster Carbine"],
        tags: ["Commando", "Clone Force 99", "Imperial Army", "Clone Wars", "Galactic Empire"]
    },
    {
        id: 13,
        imgSrc: 'images/clones//Wrecker.jpg',
        name: 'Wrecker',
        CID: 'CT-9903',
        species: 'Human',
        gender: 'Male',
        legion: 'Bad_Batch',
        legions: 'Clone Force 99',
        homeworld: 'Kamino',
        rank: 'Commando',
        weapons: ["DC-17m Interchangeable Weapon System", "Vibro-Knife Sheath"],
        tags: ["Commando", "Clone Force 99", "Clone Wars"]
    },
    {
        id: 14,
        imgSrc: 'images/clones//Waxer.jpg',
        name: 'Waxer',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Attack_Battalion_212',
        legions: '212th Attack Battalion',
        homeworld: 'Kamino',
        death: '20 BBY, Umbara',
        rank: 'Clone Trooper',
        weapons: 'DC-15A Blaster Carbine',
        tags: ["Clone Trooper", "212th Attack Battalion", "Clone Wars"]
    },
    {
        id: 15,
        imgSrc: 'images/clones//Boil.jpg',
        name: 'Boil',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Attack_Battalion_212',
        legions: '212th Attack Battalion',
        homeworld: 'Kamino',
        rank: 'Clone Trooper',
        weapons: 'DC-15A Blaster Carbine',
        tags: ["Clone Trooper", "212th Attack Battalion", "Clone Wars"]
    },
    {
        id: 16,
        imgSrc: 'images/clones//Hardcase.jpg',
        name: 'Hardcase',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: '501st Legion',
        homeworld: 'Kamino',
        death: '20 BBY, aboard a DH-Omni Support Vessel, Umbara System',
        rank: 'Clone Trooper',
        weapons: ["DC-15A Blaster Rifle", "Rapid-Fire Z-6 Rotary Blaster Cannon"],
        tags: ["Clone Trooper", "501st Legion", "Clone Wars"]
        
    },
    {
        id: 17,
        imgSrc: 'images/clones//Thorn.jpg',
        name: 'Thorn',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Coruscant',
        legions: 'Coruscant Guard',
        homeworld: 'Kamino',
        death: '19 BBY, Scopio',
        rank: ["Shock Trooper", "Commander"],
        weapons: 'Z-6 Rotary Blaster Cannon',
        tags: ["Shock Trooper", "Commander", "Coruscant Guard", "Clone Wars"]
    },
    {
        id: 18,
        imgSrc: 'images/clones//Thire.jpg',
        name: 'Thire',
        CID: 'CC-4477',
        legion: 'Coruscant',
        legions: 'Coruscant Guard',
        homeworld: 'Kamino',
        rank: ["Shock Trooper", "Officer"],
        weapons: ["DC-17 Repeater Hand Blasters", "DC-15A Blaster Rifle", "RPS-6 Rocket Launcher"],
        tags: ["Shock Trooper", "Officer", "Coruscant Guard", "Clone Wars"]
    },
    {
        id: 19,
        imgSrc: 'images/clones//Jek.webp',
        name: 'Jek',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Elite_Corps_41',
        legions: ["41st Elite Corps", "Coruscant Guard"],
        homeworld: 'Kamino',
        death: '19 BBY, Kashyyyk',
        rank: ["Shock Trooper", "Captain"],
        weapons: ["DC-17 Hand Blaster", "Z-6 Rotary Blaster Cannon", "RPS-6 Rocket"],
        tags: ["Shock Trooper", "Captain", "41st Elite Corps", "Coruscant Guard", "Clone Wars"]
    },
    {
        id: 20,
        imgSrc: 'images/clones//Rys.jpg',
        name: 'Rys',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Coruscant',
        legions: ["Coruscant Guard", "Yoda's Guard"],
        homeworld: 'Kamino',
        rank: "Shock Trooper",
        weapons: 'DC-15A Blaster Carbine',
        tags: ["Shock Trooper", "Coruscant Guard", "Yoda's Guard", "Clone Wars"]
    },
    {
        id: 21,
        imgSrc: 'images/clones//Longshot.jpg',
        name: 'Longshot',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Attack_Battalion_212',
        legions: '212th Attack Battalion',
        homeworld: 'Kamino',
        death: '20 BBY, Lola Sayu',
        rank: 'Clone Trooper',
        weapon: 'DC-15A Blaster Carbine',
        tags: ["Clone Trooper", "212th Attack Battalion", "Clone Wars"]
    },
    {
        id: 22,
        imgSrc: 'images/clones//Neyo.jpg',
        name: 'Neyo',
        CID: 'CC-8826',
        species: 'Human',
        gender: 'Male',
        legion: 'Reconnaissance',
        legions: ['91st Mobile Reconnaissance Corps', 'Imperial Army'],
        homeworld: 'Kamino',
        rank: 'ARC Trooper',
        weapon: 'Unknown',
        tags: ["ARC Trooper", "91st Mobile Reconnaissance Corps", "Imperial Army", "Clone Wars", "Galactic Empire"],
    },
    {
        id: 23,
        imgSrc: 'images/clones//Hevy.jpg',
        name: 'Hevy',
        CID: 'CT-782',
        species: 'Human',
        gender: 'Male',
        legion: 'Domino_Squad',
        legions: ["Domino Squad", "Rishi Station Unit"],
        homeworld: 'Kamino',
        death: '22 BBY, Rishi Moon',
        rank: 'Commander',
        weapons: 'Z-6 Rotary Blaster Cannon',
        tags: ["Commander", "Domino Squad", "Rishi Station Unit", "Clone Wars"]
    },
    {
        id: 24,
        imgSrc: 'images/clones//Gree.jpg',
        name: 'Gree',
        CID: 'CC-1004',
        species: 'Human',
        gender: 'Male',
        legion: 'Elite_Corps_41',
        legions: '41st Elite Corps',
        homeworld: 'Kamino',
        death: '19 BBY, Kashyyyk',
        rank: 'Commander',
        weapons: ["DC-15 Blaster Carbine", "DC-17 Hand Blaster"],
        tags: ["Commander", "41st Elite Corps", "Clone Wars"]    
    },
    {
        id: 25,
        imgSrc: 'images/clones//Buzz.jpg',
        name: 'Buzz',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Elite_Corps_41',
        legions: '41st Elite Corps',
        homeworld: 'Kamino',
        death: '21 BBY, Genosis',
        rank: 'Squad Leader',
        weapons: ["DC-15A Blaster Carbine", "DC-17 Hand Blaster"],
        tags: ["Squad Leader", "41st Elite Corps", "Clone Wars"]
    },
    {
        id: 26,
        imgSrc: 'images/clones//Draa.jpg',
        name: 'Draa',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Elite_Corps_41',
        legions: '41st Elite Corps',
        homeworld: 'Kamino',
        rank: 'Clone Trooper',
        weapons: ["Z-6 Rotary Blaster Cannon", "DC-15A Blaster Carbine", "DC-15A Blaster Rifle"],
        tags: ["Clone Trooper", "41st Elite Corps", "Clone Wars"]
    },
    {
        id: 27,
        imgSrc: 'images/clones//Hawk.jpg',
        name: 'Hawk',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: ["501st Legion", "Republic Starfighter Corps"],
        homeworld: 'Kamino',
        rank: ["Clone Lieutenant", "Pilot"],
        tags: ["Clone Lieutenant", "Pilot", "501st Legion", "Republic Starfighter Corps", "Clone Wars"]
    },
    {
        id: 28,
        imgSrc: 'images/clones//Oddball.jpg',
        name: 'Davijaan',
        name2: 'Oddball',
        CID: 'CC-2237',
        species: 'Human',
        gender: 'Male',
        legion: 'Squad_Seven',
        legions: 'Clone Flight Squad Seven',
        homeworld: 'Kamino',
        rank: ["Commander", "Pilot"],
        tags: ["Commander", "Pilot", "Clone Flight Squad Seven", "Clone Wars", "Galactic Empire"]
    },
    {
        id: 29,
        imgSrc: 'images/clones//Cut_Lawquane.jpg',
        name: 'Cut Lawquane',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legions: 'Grand Army of the Republic',
        spouse: 'Suu Lawquane',
        children: ["Jek Lawquane", "Shaeeah Lawquane"],
        homeworld: 'Kamino',
        rank: 'Clone Trooper',
        weapons: ["DC-15A Blaster Rifle", "DC-15A Blaster Carbine"],
        tags: ["Clone Trooper", "Grand Army of the Republic"]
    },
    {
        id: 30,
        imgSrc: 'images/clones//Comet.jpg',
        name: 'Comet',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Battalion_104',
        legions: '104th Battalion',
        homeworld: 'Kamino',
        rank: 'Corporal',
        weapon: 'DC-15A Blaster Carbine',
        tags: ["Corporal", "104th Battalion", "Clone Wars"]
    },
    {
        id: 31,
        imgSrc: 'images/clones//Boost.jpg',
        name: 'Boost',
        CID: 'CT-4860',
        species: 'Human',
        gender: 'Male',
        legion: 'Battalion_104',
        legions: '104th Battalion',
        homeworld: 'Kamino',
        rank: 'Clone Trooper',
        weapon: 'DC-15A Blaster Carbine',
        tags: ["Clone Trooper", "104th Battalion", "Clone Wars"]
    },
    {
        id: 32,
        imgSrc: 'images/clones//Sinker.jpg',
        name: 'Sinker',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Battalion_104',
        legions: '104th Battalion',
        homeworld: 'Kamino',
        rank: 'Sergeant',
        weapons: 'DC-15A Blaster Carbine',
        tags: ["Sergeant", "104th Battalion", "Clone Wars"]
    },
    {
        id: 33,
        imgSrc: 'images/clones//Ponds.jpg',
        name: 'Ponds',
        CID: 'CT-411',
        species: 'Human',
        gender: 'Male',
        legion: 'Reconnaissance',
        legions: '91st Mobile Reconnaissance Corps',
        homeworld: 'Kamino',
        rank: 'Officer',
        weapons: 'DC-17 Blaster Pistols',
        tags: ["Officer", "91st Mobile Reconnaissance Corps", "Clone Wars"]
    },
    {
        id: 34,
        imgSrc: 'images/clones//Trapper.jpg',
        name: 'Trapper',
        CID: 'CC-8826',
        species: 'Human',
        gender: 'Male',
        legion: 'Attack_Battalion_212',
        legions: '212th Recon Division',
        homeworld: 'Kamino',
        rank: 'Clone Trooper',
        weapons: 'Unknown',
        tags: ["Clone Trooper", "212th Recon Division", "Clone Wars"]
    },
    {
        id: 35,
        imgSrc: 'images/clones//Wooley.jpg',
        name: 'Wooley',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Attack_Battalion_212',
        legions: ["212th Attack Battalion", "Ghost Company"],
        homeworld: 'Kamino',
        rank: 'Clone Trooper',
        weapons: 'DC-15A Blaster Rifle',
        tags: ["Clone Trooper", "212th Attack Battalion", "Ghost Company", "Clone Wars"]
    },
    {
        id: 36,
        imgSrc: 'images/clones//Stone.jpg',
        name: 'Stone',
        CID: 'CC-5869',
        species: 'Human',
        gender: 'Male',
        legion: 'Coruscant',
        legions: 'Coruscant Guard',
        homeworld: 'Kamino',
        rank: ["Shock Trooper", "Commander"],
        weapons: 'Unknown',
        tags: ["Shock Trooper", "Commander", "Coruscant Guard", "Clone Wars"]
    },
    {
        id: 37,
        imgSrc: 'images/clones//Doom.jpg',
        name: 'Doom',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Doom_Unit',
        legions: "Doom's Unit",
        homeworld: 'Kamino',
        rank: 'Commander',
        weapons: 'Blaster Pistols',
        tags: ["Commander", "Doom's Unit", "Clone Wars"]   
    },
    {
        id: 38,
        imgSrc: 'images/clones//Lock.jpg',
        name: 'Lock',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Eeth_Koth_Unit',
        legions: "Eeth Koth's Unit",
        homeworld: 'Kamino',
        rank: 'Captain',
        weapon: 'DC-15A Blaster Carbine',
        tags: ["Captain", "Eeth Koth's Unit", "Clone Wars"]
    },
    {
        id: 39,
        imgSrc: 'images/clones//Stak.jpg',
        name: 'Stak',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Reconnaissance',
        legions: ["Lightning Squadron", "91st Mobile Reconnaissance Corps"],
        homeworld: 'Kamino',
        rank: 'ARF Trooper',
        tags: ["ARF Trooper", "Lightning Squadron", "91st Mobile Reconnaissance Corps", "Clone Wars"]
    },
    {
        id: 40,
        imgSrc: 'images/clones//Razor.jpg',
        name: 'Razor',
        CID:'CT-6910',
        species: 'Human',
        gender: 'Male', 
        legion: 'Reconnaissance',
        legions: ["Lightning Squadron", "91st Mobile Reconnaissance Corps"],
        homeworld: 'Kamino',
        rank: 'ARF Trooper',
        tags: ["ARF Trooper", "Lightning Squadron", "91st Mobile Reconnaissance Corps", "Clone Wars"]  
    },
    {
        id: 41,
        imgSrc: 'images/clones//Colt.jpg',
        name: 'Colt',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Rancor_Battalion',
        legions: 'Rancor Battalion',
        homeworld: 'Kamino',
        death: '21 BBY, Kamino',
        rank:["ARC Commander", "ARC Trooper"],
        weapons: 'Unknown',
        tags: ["ARC Commander", "ARC Trooper", "Rancor Battalion", "Clone Wars"]
    },
    {
        id: 42,
        imgSrc: 'images/clones//Havoc.jpg',
        name: 'Havoc',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Rancor_Battalion',
        legions: 'Rancor Battalion',
        homeworld: 'Kamino',
        death: '21 BBY, Kamino',
        rank: ["ARC Trooper", "ARC Commander"],
        weapon: 'DC-15A Blaster Rifle',
        tags: ["ARC Commander", "ARC Trooper", "Rancor Battalion", "Clone Wars"]


    },
    {
        id: 43,
        imgSrc: 'images/clones//Blitz.jpg',
        name: 'Blitz',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Rancor_Battalion',
        legions: 'Rancor Battalion',
        homeworld: 'Kamino',
        rank: ["ARC Trooper", "ARC Commander"],
        weapons: ["Twin DC-17s Pistol Blasters"],
        tags: ["ARC Commander", "ARC Trooper", "Rancor Battalion", "Clone Wars"]
    },
    {
        id: 44,
        imgSrc: 'images/clones//Bly.jpg',
        name: 'Bly',
        CID: 'CC-5052',
        species: 'Human',
        gender: 'Male',
        legion: 'Star_Corps_327',
        legions: ["327th Star Corps", "Stormtrooper Corps"],
        homeworld: 'Kamino',
        rank: ["Officer", "ARC Trooper"],
        weapons: ["DC-15A Blaster Rifle", "DC-15A Blaster Carbine"],
        tags: ["Officer", "ARC Trooper", "327th Star Corps", "Stormtrooper Corps", "Clone Wars", "Galactic Empire"]
    },
    {
        id: 45,
        imgSrc: 'images/clones//Droidbait.jpg',
        name: 'Droidbait',
        CID: 'CT-00-2010',
        species: 'Human',
        gender: 'Male',
        legion: 'Domino_Squad',
        legions: ["Domino Squad", "Rishi Station Unit"],
        homeworld: 'Kamino',
        rank: 'Clone Trooper',
        weapon: 'DC-15A Blaster Carbine',
        tags: ["Clone Trooper", "Rishi Station Unit", "Domino Squad", "Clone Wars"]
    },
    {
        id: 46,
        imgSrc: 'images/clones//Cutup.jpg',
        name: 'Cutup',
        CID: 'CT-4040',
        species: 'Human',
        gender: 'Male',
        legion: 'Domino_Squad',
        legions: ["Domino Squad", "Rishi Station Unit"],
        homeworld: 'Kamino',
        death: '22 BBY, Rishi Moon',
        rank: 'Clone Trooper',
        weapons: 'Unknown',
        tags: ["Clone Trooper", "Domino Squad", "Rishi Station Unit", "Clone Wars"]
    
    },
    {
        id: 47,
        imgSrc: 'images/clones//Charger.jpg',
        name: 'Charger',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: '50st Legion',
        homeworld: 'Kamino',
        death: '20 BBY, Lola Sayu',
        rank: 'Clone Trooper',
        weapon: 'DC-15A Blaster Carbine',
        tags: ["Clone Trooper", "501st Legion", "Clone Wars"]
    },
    {
        id: 48,
        imgSrc: 'images/clones//Hound.jpg',
        name: 'Hound',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Coruscant',
        legions: 'Coruscant Guard',
        homeworld: 'Kamino',
        rank: 'ARF Scout Trooper Sergeant',
        weapons: ["DC-17 Blaster Pistol", "DC-15s Blaster"],
        tags: ["ARF Scout Trooper Sergeant", "Coruscant Guard", "Clone Wars"]

    },
    {
        id: 49,
        imgSrc: 'images/clones//Keeli.jpg',
        name: 'Keeli',
        CID: 'Unknown',
        species: 'Human',
        gender: 'Male',
        legion: 'Outer_Rim_Garrison',
        legions: 'Outer Rim Garrison',
        homeworld: 'Kamino',
        death: '22 BBY, Ryloth',
        rank: 'Captain',
        weapons: 'DC-17 Hand Blasters',
        tags: ["Captain", "Outer Rim Garrison", "Clone Wars"]
    },
    {
        id: 50,
        imgSrc: 'images/clones//Dogma.jpg',
        name: 'Dogma',
        CID: 'CT-6922',
        species: 'Human',
        gender: 'Male',
        legion: 'Legion_501',
        legions: '501st Legion',
        homeworld: 'Kamino',
        rank: 'Private',
        weapon: 'DC-15A Blaster',
        tags: ["Private", "501st Legion", "Clone Wars"]
    }

]