export const hrJedi = [
    
        {
            id: 1,
            imgSrc: 'images/hrjedi/AvarKriss.webp',
            name: 'Avar Kriss',
            birth: '262 BBY',
            species: 'Human',
            gender: 'Female',
            spouse: 'Elzar Mann',
            masters: 'Cherff Maota',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            nine: 'Luminous Nine',
            conclave: '232 BBY',
            emergences: '232 BBY',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Master", "Green", "High Republic", "Luminous Nine", "Starlight Beacon Conclave", "Emergences", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 2,
            imgSrc: 'images/hrjedi/StellanGios.webp',
            name: 'Stellan Gios',
            death: '230 BBY, Starlight Beacon, Eiram',
            species: 'Human',
            gender: 'Male',
            masters: 'Rana Kant',
            padawans: 'Vernestra Rwoh',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            council: '232-230 BBY, replaced Rana Kant',
            red: 'Red Group',
            emergences: '232 BBY',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Master", "Blue", "High Republic", "Jedi High Council", "Emergences", "Nihil Conflict", "Drengir Crisis", "Red Group"]
        },
        {
            id: 3,
            imgSrc: 'images/hrjedi/ElzarMann.webp',
            name: 'Elzar Mann',
            name2: 'Laserman',
            species: 'Human',
            gender: 'Male',  
            spouse: 'Avar Kriss',
            master: 'Roland Quarry',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',    
            nine: 'Luminous Nine',
            emergences: '232 BBY',
            nihil: '232-229 BBY',
            tags: ["Human", "Jedi Master", "Blue", "High Republic", "Emergences", "Nihil Conflict", "Luminous Nine"]
        },
        {
            id: 4,
            imgSrc: 'images/hrjedi/VernestraRwoh.webp',
            name: 'Vernestra Rwoh',
            homeworld: 'Coruscant',
            birth: '248 BBY',
            species: 'Mirialan', 
            gender: 'Female',
            masters: 'Stellan Gios',
            padawans: ["Imri Cantaros", "Qimir"],
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'purple',
            secondary: 'Secondary Team',
            red: 'Red Group',
            emergences: '232 BBY',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Mirialan", "Jedi Master", "Purple", "High Republic", "Emergences", "Nihil Conflict", "Drengir Crisis", "Secondary Team", "Red Group"],
            movies: ["The Acolyte"]
        },
        {
                id: 7,
                imgSrc: 'images/hrjedi/BellZettifar.webp',
                name: 'Bell Zettifar',
                homeworld: 'Chandrila',
                birth: '250 BBY, Chandrila',
                species: 'Human',
                gender: 'Male',
                masters: ["Loden Greatstorm", "Indeera Stokes"],
                rank: 'Jedi Knight',
                ranks: 'Knight',
                lightsaber: 'green',
                nine: 'Luminous Nine',
                emergences: '232 BBY',
                nihil: '232-230 BBY',
                drengir: '232-231 BBY',
                tags: ["Human", "Jedi Knight", "Green", "Luminous Nine", "Emergences", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 6,
            imgSrc: 'images/hrjedi/LodenGreatstorm.webp',
            name: 'Loden Greatstorm',
            death: '231 BBY, Grizal',
            species: "Twi'lek",
            gender: 'Male',
            padawans: 'Bell Zettifar',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'yellow',
            emergences: '232 BBY',
            nihil: '232-231 BBY',
            tags: ["Twi'lek", "Jedi Master", "Yellow", "High Republic", "Emergences", "Nihil Conflict"]
        },
        {
            id: 4,
            imgSrc: 'images/hrjedi/IndeeraStokes.webp',
            name: 'Indeera Stokes',
            species: 'Tholothian',
            gender: 'Female', 
            padawans: 'Bell Zettifar',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'yellow',
            secondary: 'Secondary Team',
            emergences: '232 BBY',
            nihil: '232-230 BBY',
            tags: ["Tholothian", "Jedi Master", "Yellow", "High Republic", "Secondary Team", "Emergences", "Nihil Conflict"]
        },
        {
            id: 21,
            imgSrc: 'images/hrjedi/KeeveNoto.webp',
            name: 'Keeve Trennis',
            death: '3 ABY',
            species: 'Human',
            gender: 'Female',
            masters: 'Sskeer',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            keeve: "Keeve's Crew",
            stormwall: 'Stormwall Defense Fleet',
            emergences: '232 BBY',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            twenty: 'Lost Twenty',
            order66: 'Survivor',
            tags: ["Human", "Jedi Master", "Green", "High Republic", "Fall of the Jedi", "Reign of the Empire", "Age of Rebellion", "Lost Twenty", "Keeve's Crew", "Stormwall Defense Fleet", "Emergences", "Nihil Conflict", "Drengir Crisis", "Order 66 Survivors"]
        },
        {
            id: 22,
            imgSrc: 'images/hrjedi/Sskeer.webp',
            name: 'Sskeer',
            homeworld: 'Dosh',
            species: 'Trandoshan',
            gender: 'Male',
            padawans: 'Keeve Trennis',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            keeve: "Keeve's Crew",
            stormwall: 'Stormwall Defense Fleet',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Trandoshan", "Jedi Master", "Blue", "High Republic", "Keeve's Crew", "Stormwall Defense Fleet", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 14,
            imgSrc: 'images/hrjedi/ReathSilas.webp',
            name: 'Reath Silas',
            homeworld: 'Coruscant',
            birth: '249 BBY',
            species: 'Human',
            gender: 'Male',
            masters: ["Jora Malli", "Cohmac Vitus"],
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            kashyyyk: '228 BBY',
            nine: 'Luminous Nine',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Knight", "Green", "High Republic", "Kashyyyk Team", "Luminous Nine", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 24,
            imgSrc: 'images/hrjedi/OrlaJareni.webp',
            name: 'Orla Jareni',
            death: '230 BBY, Starlight Beacon, Eiram System',
            species: 'Umbaran',
            gender: 'Female',
            masters: 'Laret Soveral',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'white',
            emergences: '232 BBY',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Umbaran", "Jedi Master", "White", "High Republic", "Emergences", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 11,
            imgSrc: 'images/hrjedi/PorterEngle.webp',
            name: 'Porter Engle',
            name2: 'Blade of Bardotta',
            birth: 'By 407 BBY',
            species: 'Ikkrukkian',
            gender: 'Male',
            siblings: 'Barash Silvain',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            emergences: '232 BBY',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Ikkrukkian", "Jedi Master", "Blue", "High Republic", "Emergences", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 3,
            imgSrc: 'images/hrjedi/Imri_Cantaros.webp',
            name: 'Imri Cantaros',
            homeworld: ["Genetia", "Hynestia"],
            birth: '246 BBY',
            death: 'By 152 BBY',
            species: 'Human',
            gender: 'Male',
            masters: ["Douglas Sunvale", "Vernestra Rwoh"],
            padawans: 'Tep Tep',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            red: 'Red Group',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Knight", "Blue", "High Republic", "Red Group", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 5,
            imgSrc: 'images/hrjedi/EstalaMaru.webp',
            name: 'Estala Maru',
            death: '230 BBY, Starlight Beacon, Eiram System',
            species: 'Lessurian',
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'yellow',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Lessurian", "Jedi Master", "Yellow", "High Republic", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 10,
            imgSrc: 'images/hrjedi/MikkelSutmani.webp',
            name: 'Mikkel Sutmani',
            death: '231 BBY, Valo',
            species: 'Ithorian',
            gender: 'Male',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            conclave: '232 BBY',
            nihil: '232-231 BBY',
            tags: ["Ithorian", "Jedi Knight", "Blue", "Starlight Beacon Conclave", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/Burryaga.webp',
            name: 'Burryaga Agaburry',
            homeworld: 'Kashyyyk',
            species: 'Wookiee',
            gender: 'Male',
            masters: 'Nib Assek',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            kashyyyk: '228 BBY',
            luminous: 'Luminous Nine',
            red: 'Red Group',
            conclave: '232 BBY',
            emergences: '232 BBY',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Wookiee", "Jedi Knight", "Blue", "High Republic", "Kashyyyk Team", "Luminous Nine", "Red Group", "Starlight Beacon Conclave", "Emergences", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 17,
            imgSrc: 'images/hrjedi/Arkoff.webp',
            name: 'Arkoff',
            species: 'Wookiee',
            masters: 'Ravna Abronsa',
            padawans: ["Azlin Rell", "Lily Tora-Asi"],
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            nine: 'Luminous Nine',
            sorrow: '382 BBY',
            drengir: '232-231 BBY',
            nihil: '228 BBY',
            tags: ["Wookiee", "Jedi Master", "Green", "High Republic", "Luminous Nine", "Night of Sorrow", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 18,
            imgSrc: "images/hrjedi/TeAmi.webp",
            name: "Te'Ami",
            death: '232 BBY',
            species: 'Duros',
            gender: 'Female',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            conclave: '232 BBY',
            drengir: '232 BBY',
            tags: ["Duros", "Jedi Knight", "Blue", "Starlight Beacon Conclave", "Drengir Crisis"]
        },
        {
            id: 23,
            imgSrc: 'images/hrjedi/LilyToraAsi.webp',
            name: 'Lily Tora-Asi',
            species: 'Human',
            gender: 'Female',
            masters: 'Arkoff',
            padawans: 'Keerin Fionn',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',    
            secondary: 'Secondary Team', 
            nihil: '232-228 BBY',      
            drengir: '232-231 BBY', 
            tags: ["Human", "Jedi Knight", "Green", "Secondary Team", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 16,
            imgSrc: 'images/hrjedi/TorbanBuck.webp',
            name: 'Torban Buck',
            name2: 'Buckets of Blood',
            species: 'Chagrian',
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            secondary: 'Secondary Team',
            nine: 'Luminous Nine',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Chagrian", "Jedi Master", "Blue", "Secondary Team", "Luminous Nine", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 9,
            imgSrc: 'images/hrjedi/NibAssek.webp',
            name: 'Nib Assek',
            death: '230 BBY, Starlight Beacon, Eiram System',
            species: 'Human',
            gender: 'Female',
            padawans: 'Burryaga Agaburry',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            red: 'Red Group',
            conclave: '232 BBY',
            nihil: '232-230 BBY',
            tags: ["Human", "Jedi Knight", "Blue", "Red Group", "Starlight Beacon Conclave", "Nihil Conflict"]
        },
        {
            id: 10,
            imgSrc: 'images/hrjedi/Farzala.webp',
            name: 'Farzala Tarabal',
            species: 'Zygerrian',
            gender: 'Male',
            masters: 'Obratuk Glii',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Zygerrian", "Jedi Knight", "Green", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 15,
            imgSrc: 'images/hrjedi/LulaTalisola.webp',
            name: 'Lula Talisola',
            homeworld: 'Naboo',
            species: 'Human',
            gender: 'Female',
            spouse: 'Zeen Mrala',
            masters: ["Kantam Sy", "Yoda"],
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'blue',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Padawan", "Blue", "Nihil Conflict", "Drengir Crisis"]
        },
                {
            id: 42, 
            imgSrc: 'images/hrjedi/ZeenMrala.webp',
            name: 'Zeen Mrala',
            homeworld: 'Trymant IV',
            birth: '247 BBY',
            species: 'Mikkian',
            gender: 'Female',
            spouse: 'Lula Talisola',
            padawans: ["Yarzion Vell", "Ordea"],
            rank: 'Unknown',
            ranks: 'Unknown',
            lightsaber: 'green',
            nihil: '232-230 BBY',
            tags: ["Mikkian", "Green", "High Republic", "Nihil Conflict"]
        },
        {
            id: 19,
            imgSrc: 'images/hrjedi/RamJomaram.webp',
            name: 'Ram Jamoram',
            homeworld: 'Valo',
            birth: '245 BBY, Valo',
            species: 'Human',
            gender: 'Male',
            masters: 'Kunpar Vasivola',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'yellow',
            nihil: '232-229 BBY',
            skull: '229 BBY',
            tags: ["Human", "Jedi Padawan", "Yellow", "High Republic", "Nihil Conflict", "Scarlet Skulls"]  
        },
        {
            id: 25,
            imgSrc: 'images/hrjedi/Qort.webp',
            name: 'Qort',
            homeworld: 'Zav Alox',
            species: 'Aloxian',
            gender: 'Male',
            masters: ["Savina Besatrix Malagan", "Tabakan Pak"],
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Aloxian", "Jedi Knight", "Blue", "High Republic", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/Gavi.webp',
            name: 'Gavi Takitaken',
            birth: '243 BBY',
            species:  'Human',
            master: 'Aebal',
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'blue',
            nihil: '229-228 BBY',
            skull: '229 BBY',
            tags: ["Human", "Blue", "Youngling", "High Republic", "Scarlet Skulls", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/Kildo.webp',
            name: 'Kildo',
            homeworld: 'Valo',
            birth: '243 BBY',
            species: 'Alcedian',
            master: 'Aebal',
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'purple',
            nihil: '229 BBY',
            skull: '229-228 BBY',
            tags: ["Algerian", "Purple", "Youngling", "Scarlet Skulls", "High Republic", "Nihil Conflict"]
        },
        {
            id: 26,
            imgSrc: 'images/hrjedi/TepTep.webp',
            name: 'Tep Tep',
            homeworld: 'Valo',
            birth: '241 BBY',
            species: 'Alcedian',
            gender: 'Female',
            masters: ["Aebal", "Imri Cantaros"],
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'green',
            skull: '229 BBY',
            nihil: '229-228 BBY',
            tags: ["Alcedian", "Jedi Youngling", "Green", "High Republic", "Scarlet Skulls", "Nihil Conflict"]
        },
        {
            id: 27,
            imgSrc: 'images/hrjedi/Terec.webp',
            name: 'Terec',
            homeworld: ["Sagamore", "Kotab"],
            species: 'Kotabi',
            gender: 'Non-binary',
            sibling: 'Ceret (bond-twin)',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            nine: 'Luminous Nine',
            keeve: "Keeve's Crew",
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Kotabi", "Jedi Knight", "Green", "High Republic", "Luminous Nine", "Keeve's Crew", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 27,
            imgSrc: 'images/hrjedi/Ceret.webp',
            name: 'Ceret',
            homeworld: ["Sagamore", "Kotab"],
            species: 'Kotabi',
            gender: 'Non-binary',
            sibling: 'Ceret (bond-twin)',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            secondary: 'Secondary Team', 
            keeve: "Keeve's Crew",
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Kotabi", "Jedi Knight", "Green", "High Republic", "Secondary Team", "Keeve's Crew", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 28,
            imgSrc: 'images/hrjedi/CreightonSun.webp',
            name: 'Creighton Sun',
            birth: '422 BBY',
            death: 'By 229 BBY',
            species: 'Human',
            gender: 'Male',
            padawans: 'Enya Keen',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            eiram: '387-382 BBY',
            sorrow: '382 BBY',
            tags: ["Human", "Jedi Master", "Blue", "High Republic", "Eiram and E'ronoh War", "Night of Sorrow"]
        },
        {
            id: 29,
            imgSrc: 'images/hrjedi/KantamSy.webp',
            name: 'Kantam Sy',
            species: 'Human',
            gender: 'Non-binary',
            masters: 'Yoda',
            padawans: 'Lula Talisola',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            nihil: '232-230 BBY',
            tags: ["Human", "Jedi Master", "Green",  "High Republic", "Nihil Conflict"]
        },
        {
            id: 30,
            imgSrc: 'images/hrjedi/Zallah_Macri.webp',
            name: 'Zallah Macri',
            death: '382 BBY, Dalna',
            species: 'Soikan',
            gender: 'Female',
            padawans: 'Kevmo Zink',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            sorrow: '382 BBY',
            tags: ["Soikan", "Jedi Master", "Blue", "High Republic", "Night of Sorrow"]
        },
        {
            id: 31,
            imgSrc: 'images/hrjedi/KevmoZink.webp',
            name: 'Kevmo Zink',
            homeworld: 'Hosnian Prime',
            death: '382 BBY, Dalna',
            species: 'Pantoran',
            gender: 'Male',
            masters: 'Zallah Macri',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'yellow',
            sorrow: '382 BBY',
            tags: ["Pantoran", "Jedi Padawan", "Yellow", "High Republic", "Night of Sorrow"]
        },
        {
            id: 32,
            imgSrc: 'images/hrjedi/TyYorrick.webp',
            name: 'Ty Yorrick',
            species: 'Tholothian',
            gender: 'Female',
            masters: 'Cibaba',
            padawans: 'Drewen Qweebjillan',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'purple',
            nine: 'Luminous Nine',
            nihil: '232-230 BBY',
            drengir: '232-231 BBY',
            tags: ["Tholothian", "Jedi Padawan", "High Republic", "Luminous Nine", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 33,
            imgSrc: 'images/hrjedi/SilandraSho.webp',
            name: 'Silandra Sho',
            species: 'Human',
            gender: 'Female',
            padawans: 'Rooper Nitani',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            pathfinder: "Master Sho's Pathfinder team",
            eiram: '387-382 BBY',
            tags: ["Human", "Jedi Master", "Blue", "High Republic", "Master Sho's Pathfinder Team", "Eiram and E'ronoh War"]
        },
        {
            id: 34,
            imgSrc: 'images/hrjedi/SavMalagan.webp',
            name: 'Savina Besatrix Malagan',
            homeworld: 'Phatrong',
            birth: '397 BBY',
            species: 'Kyuzo',
            gender: 'Female',
            masters: ["Kaktorf", "Tera Sinube"],
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'purple',
            eiram: '387-382 BBY',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Kyuzo", "Jedi Master", "Purple", "High Republic", "Eiram and E'ronoh War", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 35,
            imgSrc: 'images/hrjedi/Char-Ryl-Roy.webp',
            name: 'Char-Ryl-Roy',
            death: '382 BBY, Dalna',
            species: 'Cerean',
            gender: 'Male',
            padawans: 'Enya Keen',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            council: 'until 382 BBY',
            eiram: '387-382 BBY',
            sorrow: '382 BBY',
            tags: ["Cerean", "Jedi Master", "Green", "High Republic", "Jedi High Council", "Eiram and E'ronoh War", "Night of Sorrow"]
        },
        {
            id: 36,
            imgSrc: 'images/hrjedi/EnyaKeen.webp',
            name: 'Enya Keen',
            birth: '402 BBY',
            species: 'Human',
            gender: 'Female',
            masters: ["Char-Ryl-Roy", "Creighton Sun"],
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'yellow',
            eiram: '387-382 BBY',
            sorrow: '382 BBY',
        },
        {
            id: 35,
            imgSrc: 'images/hrjedi/GellaNattai.webp',
            name: 'Gella Nattai',
            birth: '412 BBY',
            species: 'Human',
            gender: 'Female',
            masters: 'Arezi Mar',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'purple',
            pathfinder: "Gella Nattai's Pathfinder Team",
            eiram: '387-382 BBY',
            sorrow: '382 BBY',
            tags: ["Human", "Jedi Knight", "Purple", "High Republic", "Eiram and E'ronoh War", "Night of Sorrow"]
        },
        {
            id: 36,
            imgSrc: 'images/hrjedi/Santari_Khri.webp',
            name: 'Santati Khri',
            species: 'Human',
            gender: 'Female',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            nihil: '232-228 BBY',
            tags: ["Human", "Jedi Master", "Blue", "High Republic", "Nihil Conflict"]
        },
        {
            id: 37,
            imgSrc: 'images/hrjedi/Dagan_Gera.webp',
            name: 'Dagan Gera',
            death: '9 BBY, Koboh',
            species: 'Arkanian Offshoot',
            gender: 'Male',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'yellow',
            nihil: '232 BBY',
            order66: 'Survivor',
            tags: ["Arkanian Offshoot", "Jedi Knight", "Yellow", "Sith", "High Republic", "Reign of the Empire", "Order 66 Survivors", "Nihil Conflict"]
        },
        {
            id: 36,
            imgSrc: 'images/hrjedi/Sol.webp',
            name: 'Sol',
            homeworld: 'Coruscant',
            death: '132 BBY, Brendok',
            species: 'Human',
            gender: 'Male',
            padawans: ["Verosha Aniseya", "Jecki Lon"],
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            brendok: '148 BBY',
            tags: ["Human", "Jedi Master", "Blue", "High Republic", "Brendok Four"]
        },
        {
            id: 37,
            imgSrc: 'images/hrjedi/JeckiLon.webp',
            name: 'Jecki Lon',
            birth: '150 BBY',
            death: '132 BBY, Khofar',
            species: 'Theelin-Human Hybrid',
            gender: 'Female',
            masters: 'Sol',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'green',
            tags: ["Theelin-Human Hybrid", "Jedi Padawan", "Green", "High Republic"]
        },
        {
            id: 38,
            imgSrc: 'images/hrjedi/YordFandar.webp',
            name: 'Yord Fandar',
            death: '132 BBY, Khofar',
            species: 'Human',
            gender: 'Male',
            padawans: 'Tasi Lowa',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'yellow',
            tags: ["Human", "Jedi Knight", "Yellow", "High Republic"]
        },
        {
            id: 39,
            imgSrc: 'images/hrjedi/Indara.webp',
            name: 'Indara',
            birth: '178 BBY',
            death: '132 BBY, Ueda',
            species: 'Human',
            gender: 'Female',
            padawans: 'Torbin',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            brendok: '148 BBY',
            tags: ["Human", "Jedi Master", "Green", "High Republic", "Brendok Four"]
        },
        {
            id: 40,
            imgSrc: 'images/hrjedi/Torbin.webp',
            name: 'Torbin',
            homeworld: 'Bonadan',
            death: '132 BBY, Olega', 
            pecies: 'Human',
            gender: 'Male',
            masters: 'Indara',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'yellow',
            tags: ["Human", "Jedi Padawan", "Yellow", "High Republic", "Brendok Four"]
        },
        {
            id: 41,
            imgSrc: 'images/hrjedi/Kelnacca.webp',
            name: 'Kelnacca',
            homeworld: 'Kashyyyk',
            death: '132 BBY, Khofar',
            species: 'Wookiee',
            gender: 'Male',
            padawans: ["Yarzion Vell", "Ordea"],
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            kashyyyk: '228 BBY',
            nihil: '228 BBY',
            brendok: '148 BBY',
            tags: ["Wookiee", "Jedi Master", "Green", "High Republic", "Brendok Four", "Kashyyyk Team", "Nihil Conflict"]
        },
        {
            id: 43,
            imgSrc: 'images/hrjedi/KaiBrightstar.webp',
            name: 'Kai Brightstar',
            homeworld: 'Hosnian Prime',
            birth: '241 BBY',
            species: 'Human',
            gender: 'Male',
            masters: 'Zia Zaldor Zanna',
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'green',
            crimson: '233 BBY',
            nihil: '232 BBY',
            tags: ["Human", "Jedi Youngling", "Green", "High Republic", "Team Crimson Bolt", "Nihil Conflict"]
        },
        {
            id: 44,
            imgSrc: 'images/hrjedi/Lys_Solay.webp',
            name: 'Lys Solay',
            homeworld: 'Pantora',
            species: 'Pantoran',
            gender: 'Female',
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'purple',
            crimson: '233 BBY',
            nihil: '232 BBY',
            tags: ["Pantoran", "Jedi Youngling", "Purple", "High Republic", "Team Crimson Bolt", "Nihil Conflict"]
        },
        {
            id: 45,
            imgSrc: 'images/hrjedi/Nubs.webp',
            name: 'Nubs',
            homeworld: 'Myllnaab',
            species: 'Pooba',
            gender: 'Male',
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'blue',
            crimson: '233 BBY',
            nihil: '232 BBY',
            tags: ["Pooba", "Jedi Youngling", "Blue", "High Republic", "Team Crimson Bolt", "Nihil Conflict"]
        },
        {

            id: 1,
            imgSrc: 'images/hrjedi/Zia_Zaldor_Zanna.webp',
            name: 'Zia Zaldor Zanna',
            homeworld: ["Denon", "Rex Strata"],
            species: 'Human',
            gender: 'Female',
            padawans: 'Wes Vinik',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            tags: ["Human", "Jedi Master", "Blue", "High Republic"]
        },
        {
            id: 69,
            imgSrc: 'images/hrjedi/WesVinik.webp',
            name: 'Wes Vinik',
            species: 'Human',
            gender: 'Male',
            masters: 'Zia Zaldor Zanna',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'yellow',
            tags: ["Human", "Jedi Padawan", "Yellow", "High Republic"]


        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/JoraMalli.webp',
            name: 'Jora Malli',
            death: '232 BBY, Kur Nebula',
            species: 'Togruta',
            gender: 'Female',
            padawans: ["Dez Rydan", "Reath Silas"],
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'white',
            council: 'until 232 BBY, replaced by Ri Ki Sakka',
            nihil: '232 BBY',
            tags: ["Togruta", "White", "Jedi Master", "High Republic", "Jedi High Council", "Nihil Conflict"]
        },
        {
            id: 46,
            imgSrc: 'images/hrjedi/CohmacVitus.webp',
            name: 'Cohmac Vitus',
            species: 'Human',
            gender: 'Male',
            masters: 'Simmix',
            padawans: 'Reath Silas',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            kashyyyk: '228 BBY',
            secondary: 'Secondary Team',
            emergences: '232 BBY',
            nihil: '232-228 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Master", "Blue", "Kashyyyk Team", "Secondary Team", "Emergences", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 47,
            imgSrc: 'images/hrjedi/GoonralMonshi.webp',
            name: 'Goonral Monshi',
            death: '229 BBY, Kindosorn',
            species: 'Latero',
            gender: 'Male',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            nihil: '232-229 BBY',
            drengir: '232-231 BBY',
            tags: ["Latero", "Jedi Knight", "Blue", "High Republic", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 48,
            imgSrc: 'images/hrjedi/OrbaLin.webp',
            name: 'OrbaLin',
            species: 'Ugor',
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            keeve: "Keeve's Crew",
            stormwall: 'Stormwall Defense Fleet',
            drengir: '232-231 BBY',

            tags: ["Ugor", "Jedi Master", "Green", "Keeve's Crew", "Stormwall Defense Fleet", "Drengir Crisis"]

        },
        {
            id: 49,
            imgSrc: 'images/hrjedi/AzlinRell.webp',
            name: 'Azlin Rell',
            species: 'Human',
            gender: 'Male',
            masters: 'Arkoff',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            kashyyyk: '228 BBY',
            nine: 'Luminous Nine',
            sorrow: '382 BBY',
            nihil: '232-228 BBY',
            tags: ["Human", "Jedi Knight", "Blue", "Kashyyyk Team", "Luminous Nine", "Night of Sorrow", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/DezRydan.webp',
            name: 'Dez Rydan',
            species: 'Human',
            masters: 'Jora Malli',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            kashyyyk: '228 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Green", "Jedi Knight", "High Republic", "Drengir Crisis"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/AmadeoAzzazzo.webp',
            name: 'Amadeo Azzazzo',
            birth: '247 BBY',
            species: 'Human',
            masters: 'Mirro Lox',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'green',
            kashyyyk: '228 BBY',
            nihil: '232-228 BBY',
            tags: ["Human", "Green", "Jedi Padawan", "High Republic", "Kashyyyk Team", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/KirakInfila.webp',
            name: "Kirak Infil'a",
            death: "19 BBY, Al'doleem",
            species: 'Unknown',
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            secondary: 'Secondary Team',
            order66: 'Survivor (19 BBY)',
            tags: ["Jedi Master", "Green", "High Republic", "Fall of the Jedi", "Reign of the Empire", "Secondary Team", "Order 66 Survivors"],
        },
        {
            id: 49,
            imgSrc: 'images/hrjedi/ObratukGlii.webp',
            name: 'Obratuk Glii',
            birth: 'By 1231 BBY',
            death: '230 BBY, Gaze Electric',
            species: 'Parwan',
            gender: 'Male',
            padawans: 'Farzala Tarabal',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green-blue-purple',
            drengir: '232-231 BBY',
            nihil: '232-230 BBY',
            tags: ["Parwan", "Jedi Master", "Green", "Blue", "Purple", "Old Republic", "High Republic", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 50,
            imgSrc: 'images/hrjedi/Emerick.webp',
            name: 'Emerick Caphtor',
            species: 'Human',
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'yellow',
            nihil: '232-230 BBY',
            tags: ["Human", "Yellow", "Jedi Master", "High Republic", "Nihil Conflict"]
        },
        {
            id: 51,
            imgSrc: 'images/hrjedi/RegaldColl.webp',
            name: 'Regald Coll',
            death: '230 BBY, Starlight Beacon, Eiram System',
            species: 'Human',
            gender: 'Male',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'yellow',
            nihil: 'Nihil Conflict',
            tags: ["Human", "Jedi Knight", "Yellow", "High Republic", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/Bibs.webp',
            name: 'Bibbs',
            death: '230 BBY, Starlight Beacon, Eiram',
            species: 'Bravaisian',
            gender: 'Male',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'green',
            nihil: '232-230 BBY',
            tags: ["Bravaisian", "Jedi Padawan", "High Republic", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/RardalBalnar.webp',
            name: 'Rardal Balnar',
            death: '230 BBY, Starlight Beacon, Eiram System',
            species: 'Human',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'green',
            nihil: '232-230 BBy',
            tags: ["Human", "Green", "Jedi Padawan", "High Republic", "Nihil Conflict"]
        },
        {
            id: 52,
            imgSrc: 'images/hrjedi/Nooran.webp',
            name: 'Nooran',
            death: '230 BBY, Starlight Beacon, Eiram System',
            species: 'Frozian',
            gender: 'Female',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'unknown',
            nihil: '232-230 BBY',
            tags: ["Frozian", "Jedi Knight", "High Republic", "Nihil Conflict"]
        },
        {
            id: 53,
            imgSrc: 'images/hrjedi/TakabanPak.webp',
            name: 'Tabakan Pak',
            death: '228 BBY',
            species: 'Dug',
            gender: 'Male',
            padawans: 'Qort',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'unknown',
            nihil: '232-230 BBY',
            tags: ["Dug", "Jedi Master", "High Republic", "Nihil Conflict"]
        },
        {
            id: 54,
            imgSrc: 'images/hrjedi/Lulad.webp',
            name: 'Lulad',
            death: '230 BBY, Starlight Beacon',
            species: 'Human',
            gender: 'Female',
            padawans: 'Yarizon Vell',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'unknown',
            nihil: '232-230 BBY',
            tags: ["Human", "Jedi Master", "Jedi Master", "High Republic", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/XoLahru.webp',
            name: 'Xo Lahru',
            species: 'Anx',
            gender: 'Male',
            rank: 'Grand Master',
            ranks: 'Master',
            lightsaber: 'green',
            council: '382-228 BBY',
            tags: ["Anx", "Green", "Grand Master", "Jedi High Council", "High Republic"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/XinithTarl.webp',
            name: 'Xinith Tarl',
            species: 'Bith',
            gender: 'Female',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'yellow',
            council: 'By 382 BBY',
            pathfinder: 'Whitherbloom Pathfinder Team',
            eiram: "Eiram and E'ronoh War",
            tags: ["Bith", "Yellow", "Jedi Master", "Jedi High Council", "Witherbloom Pathfinder Team", "High Republic", "Eiram and E'ronoh War"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/ElaSutan.webp',
            name: 'Ela Sutan',
            species: 'Caamasi',
            gender: 'Female',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            council: 'By 382 BBY',
            sorrow: 'Night of Sorrow',
            tags: ["Caamasi", "Blue", "Jedi Master", "Jedi High Council", "High Republic", "Night of Sorrow"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/Veter.webp',
            name: 'Pra-Tre Veter',
            death: '229 BBY, Gaze Electric',
            species: 'Tarnab',
            gender: 'Male',
            rank: 'Grand Master',
            ranks: 'Master',
            lightsaber: 'blue',
            color_modal: 'blue-modal',
            council: '232-229 BBY',
            tags: ["Tarnab", "Blue", "Grand Master", "Jedi High Council", "Nihil Conflict", "High Republic"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/KeatonMurag.webp',
            name: 'Keaton Murag',
            species: 'Human',
            gender: 'Male',
            rank: 'Jedi Master',
            lightsaber: 'blue',
            council: '232 BBY-',
            tags: ["Human", "Blue", "Jedi Master", "Jedi High Council", "High Republic"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/Ada-LiCarro.webp',
            name: 'Ada-Li Carro',
            death: '228 BBY, Palagosal',
            species: 'Human',
            gender: 'Female',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            nihil: '232-228 BBY',
            council: 'until 228 BBY',
            tags: ["Human", "Blue", "Jedi Master", "Jedi High Council", "High Republic", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/TeriRosason.webp',
            name: 'Teri Rosason',
            species: 'Human',
            gender: 'Female',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            color_modal: 'green-modal',
            council: 'Jedi High Council Member',
            tags: ["Human", "Green", "Jedi Master", "Jedi High Council", "High Republic"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/Adampo.webp',
            name: 'Adampo',
            death: '228 BBY, Inad Komesh',
            species: 'Yarkora',
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'blue',
            council: 'until 228 BBY',
            tags: ["Adampo", "Blue", "Jedi Master", "Jedi High Council", "High Republic"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/RanaKant.webp',
            name: 'Rana Kant',
            death: '232 BBY',
            species: 'Duros',
            gender: 'Female',
            padawans: 'Stellan Gios',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            council: '232 BBY, replaced by Stellan Gios',
            beacon: 'Destruction of Starlight Beacon',
            tags: ["Duros", "Green", "Jedi Master", "High Republic", "Jedi High Council", "High Council"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/SoleilAgra.webp',
            name: 'Soleil Agra',
            homeworld: 'Glee Anselm',
            species: 'Nautolan',
            gender: 'Female',
            rank: 'Jedi Master',
            lightsaber: 'yellow',
            council: 'Jedi High Council Member',
            tags: ["Nautolan", "Yellow", "Jedi Master", "Jedi High Council", "High Republic"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/RyKiSaka.webp',
            name: 'Ry Ki-Sakka',
            species: 'Human',
            gender: 'Male',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'purple',
            council: '232 BBY, replaced Jora Malli',
            tags: ["Human", "Purple", "Jedi Master", "Jedi High Council", "High Republic"]
        },
        {
            id: 46,
            imgSrc: 'images/hrjedi/AdySunZee.webp',
            name: "Ady Sun'Zee",
            species: 'Mirialan',
            gender: 'Female',
            masters: 'Sylwin',
            padawans: 'Nooa',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            nihil: '232-228 BBY',
            tags: ["Human", "Jedi Youngling", "Green", "High Republic", "Nihil Conflict"]
        },
        {
            id: 1,
            imgSrc: 'images/hrjedi/AidaForte.webp',
            name: 'Aida Forte',
            death: '382 BBY, Dalna',
            species: 'Nikto',
            gender: 'Female',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            eiram: '387-382 BBY',
            sorrow: '382 BBY',
            tags: ["Nikto", "Jedi Knight", "Green", "High Republic", "Eiram and E'ronoh War", "Night of Sorrow"]
        },
        {
            id: 47,
            imgSrc: 'images/hrjedi/BindalSep.webp',
            name: 'Bindal Sep',
            death: '230 BBY, Starlight Beacon, Eiram System',
            species: 'Rodian',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'unknown',
            nihil: '232-230 BBY',
            tags: ["Rodian", "Jedi Padawan", "High Republic", "Nihil Conflict"]
        },
        {
            id: 48,
            imgSrc: 'images/hrjedi/Cibaba.webp',
            name: 'Cibaba',
            species: 'Azumel',
            gender: 'Male',
            masters: 'Coron Solstus',
            padawans: ["Tylera Yorrick", "Kilas Teradine"],
            rank: 'Jedi Master',
            ranks: 'Masters',
            lightsaber: 'unknown',    
            stormwall: 'Stormwall Defense Fleet',
            tags: ["Azumel", "Jedi Master", "High Republic", "Stormwall Defense Fleet"]
        },
        {
            id: 49,
            imgSrc: 'images/hrjedi/CoronSolstus.webp',
            name: 'Coron Solstus',
            species: 'Human',
            gender: 'Male',
            masters: ["Sula Badani", "Rok Buran"],
            padawans: 'Cibaba',
            rank: 'Unknown',
            ranks: 'Unknown',
            lightsaber: 'blue',
            pathfinder: 'Witherbloom Pathfinder Team',
            tags: ["Human", "Blue", "High Republic", "Witherbloom Pathfinder Team"]
        },
        {
            id: 50,
            imgSrc: 'images/hrjedi/IthiaPaan.webp',
            name: 'Ithia Paan',
            death: '132 BBY, Khofar',
            species: 'Kel Dor',
            gender: 'Female',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            tags: ["Kel Dor", "Jedi Knight", "Green", "High Republic"]
        },
        {
            id: 51,
            imgSrc: 'images/hrjedi/KeerinFionn.webp',
            name: 'Keerin Fionn',
            death: '230 BBY, Banchii',
            species: 'Human',
            gender: 'Male',
            masters: 'Lily Tora-Asi',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'green',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Padawan", "Green", "High Republic", "Drengir Crisis"]
        },
        {
            id: 52,
            imgSrc: 'images/hrjedi/KliasTeradine.webp',
            name: 'Klias Teradine',
            death: '241 BBY, Mount Bikja',
            species: 'Zeltron',
            gender: 'Male',
            masters: 'Ciaba',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'green',
            tags: ["Zeltron", "Jedi Padawan", "Green", "High Republic"]
        },
        {
            id: 53,
            imgSrc: 'images/hrjedi/Larti.webp',
            name: 'Larti',
            species: 'Selkath',
            padawans: 'Vildar Mac',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            tags: ["Selkath", "Jedi Master", "Green", "High Republic"]
        },
        {
            id: 54,
            imgSrc: 'images/hrjedi/Leebon.webp',
            name: 'Leebon',
            death: '382 BBY, Jedha',
            species: 'Selonian',
            gender: 'Female',
            padawans: 'Matthea Cathley',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            convocation: "Jedi Order, replaced by Matthea Cathley",
            eiram: '387-382 BBY',
            tags: ["Selonian", "Jedi Master", "Green", "Convocation of the Force", "Night of Sorrow"]
        },
        {
            id: 55,
            imgSrc: 'images/hrjedi/Lyssa-votz.webp',
            name: 'Lyssa Votz',
            species: 'Human',
            gender: 'Female',
            masters: 'Nyla Quinn',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'cyan',
            nihil: '232-228 BBY',
            tags: ["Human", "Jedi Knight", "Cyan", "High Republic", "Nihil Conflict"]
        },
        {
            id: 56,
            imgSrc: 'images/hrjedi/MirroLox.webp',
            name: 'Mirro Lox',
            death: '228 BBY, Angoth',
            species: 'Human',
            gender: 'Male',
            padawans: 'Amadeo Azzazzo',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'unknown',
            tags: ["Human", "Jedi Master", "High Republic"]
        },
        {
            id: 57,
            imgSrc: 'images/hrjedi/MattheaCathley.webp',
            name: 'Matthea Cathley',
            species: "Twi'lek",
            gender: 'Female',
            masters: ["Leebon", "Vildar Mac"],
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'blue',
            convocation: 'Jedi Order',
            eiram: '387-382 BBY',
            sorrow: '382 BBY',
            tags: ["Twi'lek", "Jedi Padawan", "Blue", "High Republic", "Convocation of the Force", "Eiram and E'ronoh War", "Night of Sorrow"]
        },
        {
            id: 57,
            imgSrc: 'images/hrjedi/Nima.webp',
            name: 'Nima Allets',
            species: 'Human',
            gender: 'Female',
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'blue',
            nihil: '228 BBY',
            drengir: '232-231 BBY',
            tags: ["Human", "Jedi Youngling", "Blue", "High Republic", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 58,
            imgSrc: 'images/hrjedi/Nyla-quinn.webp',
            name: 'Nyla Quinn',
            species: "Twi'lek",
            gender: 'Female',
            padawans: 'Lyssa Votz',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'unknown',
            tags: ["Twi'lek", "Jedi Master", "High Republic"]
        },
        {
            id: 59,
            imgSrc: 'images/hrjedi/OliviahZeveron.webp',
            name: 'Oliviah Zeveron',
            species: 'Human',
            gender: 'Female',
            siblings: 'Elecia Zeveron',
            masters: 'Fitan',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            convocation: 'Jedi Order',
            eiram: '387-382 BBY',
            sorrow: '382 BBY',
            tags: ["Human", "Jedi Knight", "Green", "High Republic", "Convocation of the Force", "Eiram and E'ronoh War", "Night of Sorrow"]
        },
        {
            id: 61,
            imgSrc: 'images/hrjedi/Ordea.webp',
            name: 'Ordea',
            species: 'Human',
            gender: 'Female',
            master: ["Yarizon Vell", "Kelnacca"],
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'blue',
            tags: ["Human", "Jedi Padawan", "Blue", "High Republic"]
        },
        {
            id: 62,
            imgSrc: 'images/hrjedi/Ravna_Abronsa.webp',
            name: 'Ravna Abraonsa',
            death: '382 BBY, Dalna',
            species: 'Human',
            gender: 'Female',
            padawans: 'Arkoff',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'purple',
            sorrow: '382 BBY',
            tags: ["Human", "Jedi Master", "Purple", "High Republic", "Night of Sorrow"]
        },
        {
            id: 63,
            imgSrc: 'images/hrjedi/RokBuran.webp',
            name: 'Rok Buran',
            species: 'Human',
            gender: 'Male',
            padawans: ["Maliq", "Coron Solstus"],
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            pathfinder: 'Witherbloom Pathfinder Team',
            twoFiveExpedition: '382 BBY',
            tags: ["Human", "Jedi Master", "Green", "High Republic", "Witherbloom Pathfinder Team"]
        },
        {
            id: 65,
            imgSrc: 'images/hrjedi/RooperNitani.webp',
            name: 'Rooper Nitani',
            homeworld: 'Rohm',
            birth: '397 BBY, Rohm',
            species: 'Human',
            gender: 'Female',
            masters: 'Silandra Sho',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'blue',
            pathfinder: "Master Sho's Pathfinder Team",
            tags: ["Human", "Jedi Knight", "Blue", "High Republic", "Master Sho's Pathfinder Team"]
        },
        {
            id: 66,
            imgSrc: 'images/hrjedi/SulaBadani.webp',
            name: 'Sula Badani',
            death: '382 BBY',
            species: 'Human',
            gender: 'Female',
            padawans: 'Coron Solstus',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'yellow',
            pathfinder: 'Witherbloom Pathfinder Team',
            tags: ["Human", "Jedi Master", "Yellow", "High Republic", "Witherbloom Pathfinder Team"]
        },
        {
            id: 67,
            imgSrc: 'images/hrjedi/TasiLowa.webp',
            name: 'Tasi Lowa',
            species: 'Zygerrian',
            gender: 'Female',
            masters: 'Yord Fandar',
            rank: 'Jedi Padawan',
            ranks: 'Padawan',
            lightsaber: 'unknown',
            tags: ["Zygerrian", "Jedi Padawan", "High Republic"]
        },
        {
            id: 68,
            imgSrc: 'images/hrjedi/VildarMac.webp',
            name: 'Vildar Mac',
            homeworld: 'Kiffex',
            birth: '437 BBY, Kiffex',
            death: '228 BBY',
            species: 'Kiffar',
            gender: 'Male',
            spouse: 'Tey Sirrek',
            masters: 'Larti',
            padawans: 'Matthea Cathley',
            rank: 'Jedi Master',
            ranks: 'Master',
            lightsaber: 'green',
            convocation: 'Jedi Order',
            eiram: '387-382 BBY',
            tags: ["Kiffar", "Jedi Master", "Green", "High Republic", "Convocation of the Force", "Eiram and E'ronoh War"]
        },
        {
            id: 68,
            imgSrc: 'images/hrjedi/Vivnia_Niaviv.webp',
            name: "Via'Nia Nia'Viv",
            species: 'Togruta',
            gender: 'Female',
            rank: 'Jedi Youngling',
            ranks: 'Youngling',
            lightsaber: 'blue',
            nihil: '228 BBY',
            drengir: '232-231 BBY',
            tags: ["Togruta", "Jedi Younglings", "Blue", "High Republic", "Nihil Conflict", "Drengir Crisis"]
        },
        {
            id: 69, 
            imgSrc: 'images/hrjedi/Yacek-sparkburn.webp',
            name: 'Yacek Sparkburn',
            species: 'Human',
            gender: 'Male',
            rank: 'Jedi Knight',
            ranks: 'Knight',
            lightsaber: 'green',
            nihil: '232-228 BBY',
            tags: ["Human", "Jedi Knight", "Green", "High Republic", "Nihil Conflict"]
        }
]