export const jedi = [
    {
        id: 'yoda',
        imgSrc: 'images/jedi/yoda.jpeg',
        imgSrc2: 'images/jedi/Yoda_Wallpaper.jpeg',
        name: 'Yoda',
        homeworld: 'Unknown',
        birth: '896 BBY',
        death: '4 ABY, Dagobah',
        species: "Yoda's species",
        gender: 'Male',
        padawans: ['Kantam Sy', ' Lula Talisola', ' Dooku', ' Cin Drallig', ' Mace Windu', ' Ki-Adi Mundi', ' Obi-Wan Kenobi', ' Anakin Skywalker', ' Luke Skywalker', ' 7th Sister', ' Reva Sevander'],
        rank: 'Grand Master',
        ranks: 'Master',
        lightsaber: 'green',
        midochlorians: '16,900',
        council: '382-19BBY (19 BBY-4 ABY)',
        stark: 'Stark Hyperspace War',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi General(22-19 BBY)',
        order66: 'Survivor',
        tags: ["Yoda Species", "Green", "Grand Master", "Jedi High Council", "High Republic", "Fall of the Jedi", "Reign of the Empire", "Age of Rebellion", "Nihil Conflict", "Night of Sorrow", "Stark Hyperspace War", "Jedi Assault Team", "Clone Wars", "Order 66 Survivors"],
        movies: ["Star Wars: Young Jedi Adventures", "Acolyte", "Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Star Wars Rebels", "Star Wars V: The Empire Strikes Back", "Star Wars VI: Return of the Jedi", "Star Wars X: The Last Jedi", "Tales of the Jedi"]
    },
    {
        id: 'qui-gon',
        imgSrc: 'images/jedi/Qui-Gon_Jinn.jpeg',
        imgSrc2: "images/jedi/Qui-Gon_Jinn_Wallpaper.jpeg",
        name: 'Qui-Gon Jinn',
        homeworld: 'Coruscant',
        birth: '80 BBY, Coruscant',
        death: '32 BBY, Naboo',
        species: 'Human',
        gender: 'Male',
        masters: 'Dooku',
        padawans: 'Obi-Wan Kenobi',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        midochlorians: '17,500',
        clan: 'Heliost Clan',
        stark: 'Stark Hyperspace War',
        numidian: '66 BBY',
        tags: ["Human", "Green", "Jedi Master", "Fall of the Jedi", "Heliost Clan", "Stark Hyperspace War"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars: The Clone Wars", "Obi-Wan Kenobi", "Tales of the Jedi"]
    },
    {
        id: 'obi-wan',
        imgSrc: 'images/jedi/ObiwanKenobi.webp',
        imgSrc2: "images/jedi/jedi/Obi-wan-wallpaper.jpeg",
        name: 'Obi-Wan Kenobi',
        homeworld: 'Stewjon',
        birth: '57 BBY, Stewjon',
        death: '0 BBY, DS-1 Death Star Mobile Battle Station, Alderaan System',
        species: 'Human',
        gender: 'Male',
        masters: ["Qui-Gon Jinn", "Yoda"],
        padawans: ["Anakin Skywalker", "Luke Skywalker"],
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        midochlorians: '13,400',
        clan: 'Kybuck Clan (49 BBY)',
        stark: 'Stark Hyperspace War',
        assault: 'Jedi Assault Team (22 BBY)',
        council: '21-19 BBY(replaced Depa Billaba)',
        order66: 'Survivor (19-0 BBY)',
        tags: ["Human", "Blue", "Jedi Master", "Jedi High Council", "Fall of the Jedi", "Reign of the Empire", "Age of Rebellion", "Kybuck Clan", "Stark Hyperspace War", "Jedi Assault Team", "Clone Wars", "Order 66 Survivors", "Hidden Path", "Galactic Civil War", "Rebel Alliance"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Obi-Wan Kenobi", "Star Wars Rebels", "Star Wars IV: A New Hope", "Star Wars V: The Empire Strikes Back", "Star Wars VI: Return of the Jedi", "Tales of the Jedi", "Tales of the Underworld"]
    },
    {
        id: 'anakin',
        imgSrc: 'images/jedi/Anakin_Skywalker.jpg',
        imgSrc2: 'images/jedi/Anakin-wallpaper.jpeg',
        name: 'Anakin Skywalker',
        name2: 'Darth Vader',
        homeworld: 'Tatooine',
        birth: '41 BBY, Tatooine',
        death: '4 ABY, DS-2 Death Star II Mobile Battle Station, Endor System',
        species: 'Human',
        gender: 'Male',
        father: 'Cliegg Lars',
        mother: 'Shmi Skywalker Lars',
        spouse: 'Padme Amidala',
        siblings: 'Owen Lars (step-brother)',
        children: ["Luke Skywalker", " Leia Skywalker Organa Solo"],
        masters: ["Yoda", "Obi-Wan Kenobi", "Darth Sidious"],
        padawans: "Ahsoka Tano",
        rank: 'Jedi Knight',
        ranks: 'Knight',
        lightsaber: 'blue',
        midochlorians: '27,000',
        assault: 'Jedi Assault Team (22 BBY)',
        council: '19 BBY (replaced Oppo Rancisis)',
        clone: 'Jedi Generl (22-19 BBY)',
        sith: 'Darth Vader(19 BBY-4 ABY)',
        tags: ["Human", "Jedi Knight", "Blue", "Jedi High Council", "Fall of the Jedi", "Reign of the Empire", "Age of Rebellion",  "Jedi Assault Team", "Clone Wars", "Jedi General",  "Sith", "Galactic Civil War"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Obi-Wan Kenobi", "Star Wars Rebels", "Rogue One: A Star Wars Story", "Star Wars IV: A New Hope", "Star Wars V: The Empire Strikes Back", "Star Wars VI: Return of the Jedi", "Ahsoka", "Tales of the Jedi", "Tales of the Empire"]
    },
    {
        id: 'ahsoka',
        imgSrc: 'images/jedi/Ahsoka-Tano.webp',
        name: 'Ahsoka Tano',
        homeworld: 'Shili',
        birth: '36 BBY, Shili',
        species: 'Togruta',
        gender: 'Female',
        father: 'Nak-il Tano',
        mother: 'Pav-ti Tano',
        masters: 'Anakin Skywalker',
        padawans: 'Sabine Wren',
        rank: 'Jedi Padawan',
        ranks: 'Padawan',
        lightsaber: 'white',
        clone: 'Jedi Commander (22-19 BBY)',
        order66: 'Survivor',
        alliance: '5-3 BBY',
        tags: ["Togruta", "Jedi Padawan", "White", "Green", "Blue", "Fall of the Jedi", "Reign of the Empire", "Age of Rebellion", "New Republic", "Clone Wars", "Jedi Commander", "Order 66 Survivors", "Galactic Civil War", "Rebel Alliance"],
        movies: ["Star Wars: The Clone Wars", "Tales of the Jedi", "Star Wars Rebels", "The Mandalorian", "The Book of Boba Fett", "Ahsoka"]       
    },
    {
        id: 'luke',
        imgSrc: 'images/jedi/Luke_Skywalker.webp',
        imgSrc2: 'images/jedi/Luke_Skywalker_Wallpaper.jpeg',
        name: 'Luke Skywalker',
        homeworld: 'Tatooine',
        birth: '19 BBY, Polis Massa',
        death: '34 ABY, Ahch-To',
        species: 'Human',
        gender: 'Male',
        father: 'Anakin Skywalker',
        mother: 'Padme Amidala',
        siblings: 'Leia Skywalker Organa Solo',
        masters: ["Obi-Wan Kenobi", "Yoda"],
        padawans: ["Leia Skywalker Organa Solo", "Grogu", "Ben Solo", "Rey", "Hennix", "Tai", "Voe"],
        rank: 'Grand Master',
        ranks: 'Master',
        lightsaber: 'green',
        alliance: '0 BBY-4 ABY',
        luke: '5-28 ABY',
        galactic: 'Rebel Alliance (0 BBY-4 ABY)',
        tags: ["Human", "Grand Master", "Green", "Reign of the Empire", "Age of Rebellion",  "New Republic", "Rise of the First Order", "Rebel Alliance", "Luke's Jedi Order", "Galactic Civil War"],
        movies: ["Star Wars III: Revenge of the Sith", "Obi-Wan Kenobi", "Star Wars IV: A New Hope", "Star Wars V: The Empire Strikes Back", "Star Wars VI: Return of the Jedi", "The Mandalorian", "The Book of Boba Fett", "Star Wars VII: The Force Awakens", "Star Wars VIII: The Last Jedi", "Star Wars IX: Rise of Skywalker"]        
    },
    {
        id: 'leia',
        imgSrc: 'images/jedi/Leia.jpeg',
        name: 'Leia Skywalker Organa',
        homeworld: 'Alderaan',
        birth: '19 BBY, Polis Massa',
        death: '35 ABY, Ajan Kloss',
        species: 'Human',
        gender: 'Female',
        father: 'Anakin Skywalker',
        mother: 'Padme Amidala',
        siblings: 'Luke Skywalker',
        spouse: 'Han Solo',
        children: 'Ben Solo',
        masters: 'Luke Skywalker',
        padawans: 'Rey Skywalker',
        rank: 'Unknown',
        ranks: 'Unknown',
        lightsaber: 'blue',
        alliance: '5 BBY-4 ABY',
        galactic: 'Rebel Alliance(5 BBY-4 ABY)',
        luke: '5 ABY',
        resistance: '34-35 ABY',
        newWar: 'Resistance(34-35 ABY)',
        tags: ["Human", "Blue", "Reign of the Empire", "Age of Rebellion", "New Republic", "Rise of the First Order", "Rebel Alliance", "Luke's Jedi Order", "Galactic Civil War", "Resistance"],
        movies: ["Star Wars III: Revenge of the Sith", "Obi-Wan Kenobi", "Star Wars Rebels", "Rogue One: A Star Wars Story", "Star Wars IV: A New Hope", "Star Wars V: The Empire Strikes Back", "Star Wars VI: Return of the Jedi", "The Mandalorian", "The Book of Boba Fett", "Star Wars VII: The Force Awakens", "Star Wars VIII: The Last Jedi", "Star Wars IX: Rise of Skywalker"]    
    },
    {
        id: 'rey',
        imgSrc: 'images/jedi/Rey.webp',
        name: 'Rey Skywalker',
        homeworld: 'Jakku',
        birth: '15 ABY, Hyperkarn',
        species: 'Human',
        gender: 'Female',
        father: 'Dathan',
        mother: 'Miramir',
        masters: ["Luke Skywalker", "Leia Skywalker Organa"],
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'yellow',
        resistance: '34-35 ABY',
        newWar: 'Resistance (34-35 ABY)',
        tags: ["Human", "Yellow", "Jedi Padawan",  "New Republic", "Rise of the First Order", "New Jedi Order", "Resistance", "First Order-Resistance War"],
        movies: ["Star Wars VII: The Force Awakens", "Star Wars VIII: The Last Jedi", "Star Wars IX: Rise of Skywalker"]
    },
    {
        id: 'ben',
        imgSrc: 'images/jedi/Ben.webp',
        name: 'Ben Solo',
        name2: 'Kylo Ren',
        homeworld: 'Chandrila',
        birth: '5 ABY, Chandrila',
        death: '35 ABY, Exegol',
        species: 'Human',
        gender: 'Male',
        father: 'Han Solo',
        mother: 'Leia Skywalker Organa',
        masters: ["Luke Skywalker", "Darth Sidious", "Snoke"],
        rank: 'Unknown',
        ranks: 'Unknown',
        lightsaber: 'blue',
        newWar: '34-35 ABY',

        tags: ["Human", "Sith", "Blue", "Red", "Knights of Ren", "New Republic", "Rise of the First Order", "Luke's Jedi Order", "First Order-Resistance War", "First Order"],
        movies: ["Star Wars VII: The Force Awakens", "Star Wars VIII: The Last Jedi", "Star Wars IX: Rise of Skywalker"]
    },
    {
        id: 'mace',
        imgSrc: 'images/jedi/MaceWindu.webp',
        imgSrc2: 'images/jedi/Mace_Windu_Wallpaper.jpeg',
        name: 'Mace Windu',
        homeworld: 'Haruun Kal',
        birth: '72 BBY, Haruun Kal',
        death: '19 BBY, Coruscant',
        species: 'Human',
        gender: 'Male',
        masters: ["Cyslin Myr", "Yoda"],
        padawans: 'Depa Billaba',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'purple',
        midochlorians: '12,000',
        council: '50-19 BBY(replaced Katri)',
        stark: 'Stark Hyperspace War',
        ontotho: 'Battle of Ontotho (41 BBY)',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Victim',
        tags: ["Human", "Jedi Master", "Purple", "Jedi High Council", "Fall of the Jedi", "Stark Hyperspace War", "Battle of Ontotho", "Jedi Assault Team", "Clone Wars", "Jedi General", "Order 66 Victims"],
        movies: ["Star Wars I: Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Tales of the Jedi"]
    },
    {
        id: 'dooku',
        imgSrc: 'images/jedi/Dooku.webp',
        name: 'Dooku',
        name2: 'Darth Tyranus',
        homeworld: 'Serenno',
        birth: '102 BBY, Serenno',
        death: '19 BBY, Invisible Hand, Coruscant System',
        species: 'Human',
        gender: 'Male',
        father: 'Gora',
        mother: 'Anya',
        siblings: ["Ramil", "Jenza"],
        masters: ["Yoda", "Darth Sidious"],
        padawans: ["Rael Averross", "Qui-Gon Jinn", "Grievous", "Asajj Ventress", "Savage Opress", "Quinlan Vos"],
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        clan: 'Hawk-Bat Clan',
        numidian: '66 BBY',
        twenty: 'Lost Twenty',
        sith: 'Darth Tyranus (32-19 BBY)',
        tags: ["Human", "Jedi Master", "Blue", "Red", "Fall of the Jedi", "Sith", "Hawk-Bat Clan", "Clone Wars", "Numidian Prime Strike Team", "Lost Twenty", "Confederacy of Independent Systems"],
        movies: ["Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Tales of the Jedi"]
    },
    {
        id: 'mundi',
        imgSrc: 'images/jedi/KiAdiMundi.webp',
        imgSrc2: 'images/jedi/Ki-Adi_Mundi_wallpaper.jpeg',
        name: 'Ki-Adi Mundi',
        homeworld: 'Cerea',
        birth: '92 BBY, Cerea',
        death: '19 BBY, Mygeeto',
        species: 'Cerean',
        gender: 'Male',
        masters: 'Yoda',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        midochlorians: '13,500',
        council: '32-19 BBY (replaced Sifo-Dyas)',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Victim',
        tags: ["Cerean", "Jedi Master", "Blue", "Jedi High Council", "Fall of the Jedi",  "Jedi Assault Team", "Clone Wars", "Jedi General", "Order 66 Victims"],
        movies: ["Acolyte", "Star Wars I: Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Tales of the Jedi"]
    },
    {
        id: 'plo-koon',
        imgSrc: 'images/jedi/Plo_Koon.PNG',
        imgSrc2: 'images/jedi/Plo_Koon_Wallpaper.jpeg',
        name: 'Plo Koon',
        homeworld: 'Dorin',
        death: '19 BBY, Cato Neimoidia',
        species: 'Kel Dor',
        gender: 'Male',
        masters: 'Tyvokka',
        padawans: 'Butlar Swann',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        midochlorians: '12,800',
        stark: 'Stark Hyperspace War',
        council: '33-19 BBY',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Victim',
        tags: ["Kel Dor", "Blue", "Jedi Master", "Jedi High Council", "Fall of the Jedi",  "Clone Wars", "Jedi Assault Team", "Jedi General", "Order 66 Victims"],
        movies: ["Star Wars I: Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Tales of the Jedi"]
    },
    
    {
        id: 'tiin',
        imgSrc: 'images/jedi/SaeseeTiin.webp',
        imgSrc2: 'images/jedi/Saesse_Tinn_Wallpaper.jpeg',
        name: 'Saesee Tiin',
        homeworld: 'Iktotchi',
        death: '19 BBY, Coruscant',
        species: 'Iktotchi',
        gender: 'Male',
        masters: 'Omo Bouri',
        rank: "Jedi Master",
        ranks: 'Master',
        lightsaber: 'green',
        council: '40-19 BBY',
        stark: 'Stark Hyperspace War',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Victim',
        tags: ["Iktotchi", "Green", "Jedi Master", "Jedi High Council", "Fall of the Jedi",  "Stark Hyperspace War", "Jedi Assault Team", "Clone Wars", "Jedi General", "Order 66 Victims"],
        movies: ["Star Wars I: Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith"]
    },
    {
        id: 'yaddle',
        imgSrc: 'images/jedi/Yaddle.webp',
        imgSrc2: 'images/jedi/Yaddle_Wallpaper.jpeg',
        name: 'Yaddle',   
        birth: '509 BBY',
        death: '32 BBY, Coruscant',
        species: "Yoda's Species",
        gender: 'Female',
        padawans: ["Cippa Tarko", "Oppo Rancisis", "Jaro Tapal"],
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        midochlorians: '13,817',
        eiram: "E'iram and Eronoh War",
        night: 'Night of Sorrow',
        nihil: '232-132 BBY',
        council: '??-32 BBY(replaced by Shaak Ti)',
        tags: ["Yoda's Species", "Green", "Jedi Master", "Jedi High Council", "High Republic", "Fall of the Jedi",  "E'iram and Eronoh War", "Night of Sorrow", "Nihil Conflict"],
        movies: ["Star Wars I: The Phantom Menace", "Tales of the Jedi"]
    },
    {
        id: 'even-piell',
        imgSrc: 'images/jedi/EvenPiell.webp',
        imgSrc2: 'images/jedi/Even_Piell_Wallpaper.jpeg',
        name: 'Even Piell',
        homeworld: 'Lannik',
        birth: 'Lannik',
        death: '20BBY, Lola Sayu',
        species: 'Lannik',
        gender: 'Male',
        rank: "Jedi Master",
        ranks: 'Master',
        lightsaber: 'green',
        council: '33-20 BBY(replaced by Coleman Kcaj)',
        stark: 'Stark Hyperspace War',
        clone: 'Jedi General(22-20 BBY)',
        tags: ["Lannik", "Jedi Master", "Green", "Jedi High Council", "Fall of the Jedi", "Stark Hyperspace War", "Clone Wars", "Jedi General"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars"]
    },
    {
        id: 'rancisis',
        imgSrc: 'images/jedi/Oppo_rancisis.webp',
        imgSrc2: 'images/jedi/Oppo_Rancisis_Wallpaper.jpeg',
        name: 'Oppo Rancisis',
        homeworld: 'Thisspias',
        species: 'Thisspiasian',
        gender: 'Male',
        master: 'Yaddle',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        nihil: '232-132 BBY',
        council: '232-19BBY(replaced by Anakin Skywalker)',
        stark: 'Stark Hyperspace War',
        survivor: '19-??BBY',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Survivor',
        tags: ["Thisspiasian", "Green", "Jedi Master", "Jedi High Council", "High Republic", "Fall of the Jedi", "Reign of the Empire", "Nihil Conflict", "Stark Hyperspace War", "Clone Wars", "Jedi General", "Order 66 Survivors"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars"]
    },
    {
        id: 'gallia',
        imgSrc: 'images/jedi/AdiGallia.webp',
        imgSrc2: 'images/jedi/Ada_Gallia_Wallpaper.jpeg',
        name: 'Adi Gallia',
        homeworld: 'Coruscant',
        death: '19BBY, Florrum',
        species: 'Tholothian',
        gender: 'Female',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        council: '32-19 BBY(replaced by Stass Allie)',
        stark: 'Stark Hyperspace War',
        clone: 'Jedi General (22-19 BBY)',
        tags: ["Tholothian", "Blue", "Jedi Master", "Jedi High Council", "Fall of the Jedi", "Stark Hyperspace War", "Clone Wars", "Jedi General"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars"]        
    },
    {
        id: 'poof', 
        imgSrc: 'images/jedi/YaraelPoof.webp',
        imgSrc2: 'images/jedi/Yarael_Poof_Wallpaper.jpeg',
        name: 'Yarael Poof',
        homeworld: 'Quermia',
        death: '22BBY',
        species: "Quermian",
        gender: 'Male',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        council: '232-22BBY (replaced by Coleman Trebor)',
        secondary: 'Secondary Team',
        stark: 'Stark Hyperspace War',
        tags: ["Quermian", "Blue", "Jedi Master", "Jedi High Council", "High Republic", "Fall of the Jedi", "Stark Hyperspace War", "Secondary Team"],
        movies: ["Star Wars I: The Phantom Menace"]
    },
    {
        id: 'koth',
        imgSrc: 'images/jedi/EethKoth.webp',
        imgSrc2: 'images/jedi/Eeth_Koth_Wallpaper.jpeg',
        name: 'Eeth Koth',
        homeworld: 'Iridonia',
        death: '14BBY',   
        species: 'Zabrak',
        gender: 'Male',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',  
        spouse: 'Mira', 
        council: '40-19 BBY(replaced by Agen Kolar)',
        stark: 'Stark Hyperspace War',
        clone: 'Jedi General(22-20 BBY)',
        order66: 'Survivor',
        survivor: '19-14 BBY',
        tags: ["Zabrak", "Jedi Master", "Green", "Jedi High Council", "Fall of the Jedi", "Reign of the Empire", "Stark Hyperspace War", "Clone Wars", "Jedi General", "Order 66 Survivors"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars"]   
    },
    {
        id: 'billaba',
        imgSrc: 'images/jedi/DepaBillaba.webp',
        imgSrc2: 'images/jedi/Depa_Billaba_Wallpaper.jpeg',
        name: 'Depa Billaba',
        homeworld: 'Chalacta',
        death: '19BBY, Kaller',  
        species: 'Human',
        gender: 'Female',
        siblings: 'Sar Labooda',
        masters: 'Mace Windu',
        padawans: 'Caleb Dume',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        council: '40-21 BBY',
        stark: 'Stark Hyperspace War',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Victim',
        tags: ["Human", "Blue", "Jedi Master", "Jedi High Council", "Fall of the Jedi", "Stark Hyperspace War", "Clone Wars", "Jedi General", "Order 66 Victims"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "The Bad Batch"]           
    },
    {
        id: 'fisto',
        imgSrc: 'images/jedi/KitFisto.webp',
        imgSrc2: 'images/jedi/Kit_Fisto_Wallpaper.jpeg',
        name: 'Kit Fisto',
        homeworld: 'Glee Anselm',
        death: '19BBY, Coruscant',
        species: 'Nautolan',
        gender: 'Male',
        padawans: 'Nadhar Vebb',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        midochlorians: '17,300',
        clone: 'Jedi General',
        order66: 'Victim',
        assault: 'Jedi Assault Team (22 BBY)',
        council: '22-19 BBY(replaced Coleman Trebor)',
        tags: ["Nautolan", "Jedi Master", "Green", "Jedi High Council",  "Fall of the Jedi",  "Clone Wars", "Jedi General", "Jedi Assault Team", "Order 66 Victims"],
        movies: ["Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith"]      
    },
    {
        id: 'ti',
        imgSrc: 'images/jedi/Shaak_Ti.webp',
        imgSrc2: 'images/jedi/Shaak_Ti_Wallpaper.jpeg',
        name: 'Shaak Ti',
        homeworld: 'Shili',
        death: '19BBY, Coruscant',
        species: 'Togruta',
        gender: 'Female',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        midochlorians: '15,300',
        council: '32-19BBY(replaced Yaddle)',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi General',
        assault: 'Jedi Assault Team (22 BBY)',
        order66: 'Victim',
        tags: ["Togruta", "Jedi Master", "Blue", "Jedi High Council", "Fall of the Jedi",  "Jedi Assault Team", "Clone Wars", "Jedi General", "Order 66 Victims"],
        movies: ["Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith"]     
    },
    {
        id: 'trebor',
        imgSrc: 'images/jedi/ColemanTrebor.webp',
        imgSrc2: 'images/jedi/Coleman_Trebor_Wallpaper.jpeg',
        name: 'Coleman Trebor',
        homeworld: 'Sembla',
        death: '22 BBY, Genosis',
        species: 'Vurk',
        gender: 'Male',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        council: '22 BBY (replaced Yarael Poof, replaced by Kit Fisto)',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi Assault Team (22 BBY)',
        tags: ["Vurk", "Jedi Master", "Green", "Jedi High Council", "Fall of the Jedi",  "Jedi Assault Team", "Clone Wars"],
        movies: ["Star Wars II: Attack of the Clones"]
    },
    {
        id: 'kolar',
        imgSrc: 'images/jedi/Agen_Kolar.jpeg',
        imgSrc2: 'images/jedi/Agen_Kolar_Wallpaper.jpeg',
        name: 'Agen Kolar',
        homeworld: 'Coruscant',
        death: '19 BBY, Coruscant',
        species: 'Zabrak',
        gender: 'Male',
        padawans: 'Tan Yuster',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        assault: '22 BBY',
        council: '19 BBY (replaced Eeth Koth)',
        order66: 'Victim',
        tags: ["Zabrak", "Jedi Master", "Blue", "Green", "Jedi High Council", "Fall of the Jedi", "Jedi Assault Team", "Clone Wars", "Order 66 Victims"]
    },
    {
        id: 26,
        imgSrc: 'images/jedi/StassAllie-.webp',
        imgSrc2: 'images/jedi/Stass_Allie_Wallpaper.jpeg',
        name: 'Stass Allie',
        homeworld: 'Tholoth',
        death: '19 BBY, Saleucami',
        species: 'Tholothian',
        gender: 'Female',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        assault: '22 BBY',
        clone: 'Jedi General (22-19 BBY)',
        council: '19 BBY (replaced Adi Gallia)',
        order66: 'Victim',
        tags: ["Tholothian", "Jedi Master", "Green", "Jedi High Council", "Fall of the Jedi",  "Jedi Assault Team", "Clone Wars", "Order 66 Victims"]
    }, 
    {
        id: 'kcaj',
        imgSrc: 'images/jedi/Coleman_Kcaj.JPG',
        name: 'Coleman Kcaj',
        homeworld: 'Skustell',
        species: 'Ongree',
        gender: 'Male',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        council: '19 BBY',
        order66: 'Survivor',
        tags: ["Ongree", "Jedi Master", "Green", "Jedi High Council",  "Fall of the Jedi", "Reign of the Empire", "Order 66 Survivors"],
        movies: ["Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith"]
    },
    {
        id: 'sinube',
        imgSrc: 'images/jedi/Tera_Sinube.webp',
        name: 'Tera Sinube',
        homeworld: 'Cosia',
        birth: 'before 428 BBY',
        death: 'By 9 BBY',
        species: 'Cosian',
        gender: 'Male',
        padawans: ["Savina Besatrix", "Malagan", "Zng Arraira"],
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        council: '85-32 BBY',
        order66: 'Survivor (19-9 BBY)',
        tags: ["Cosian", "Jedi Master", "Blue", "High Republic", "Fall of the Jedi", "Reign of the Empire", "Jedi High Council", "Order 66 Survivors"],
        movies: ["Star Wars: The Clone Wars", "Tales of the Jedi", "Obi-Wan Kenobi"]
    },
    {
        id: 'dyas',
        imgSrc: 'images/jedi/SifoDyas.webp',
        name: 'Sifo-Dyas',
        homeworld: 'Minashee',
        birth: '102 BBY, Minashee',
        death: '32 BBY, over the Oba Diah Moon',
        species: 'Human',
        gender: 'Male',
        masters: 'Lene Kostana',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        council: '39-32 BBY (replaced by Ki-Adi Mundi)',
        clan: 'Hawk-Bat Clan',
        tags: ["Human", "Jedi Master", "Blue", "Fall of the Jedi", "Jedi High Council", "Hawk-Bat Clan"],
        movies: ["Star Wars: The Clone Wars"]
    },
    {
        id: 30,
        imgSrc: 'images/jedi/JocastaNu.webp',
        name: 'Jocasta Nu',
        homeworld: 'Coruscant',
        death: '19 BBY, Coruscant',
        species: 'Human',
        gender: 'Female',
        rank: ["Jedi Master", "Chief Librarian"],
        ranks: 'Master', 
        lightsaber: 'blue',
        council: '',
        order66: 'Survivor',
        tags: ["Human", "Jedi Master", "Chief Librarian", "Blue", "Fall of the Jedi", "Reign of the Empire", "Jedi High Council", "Order 66 Survivors"]

    },
    {
        id: 31,
        imgSrc: 'images/jedi/LuminaraUnduli.webp',
        imgSrc2: 'images/jedi/Luminara_Unduli_Wallpaper.jpeg',
        name: 'Luminara Unduli',
        homeworld: 'Mirial',
        death: 'Between 19-18 BBY, Stygeon Prime',
        species: 'Mirialan',
        gender: 'Female',
        padawans: 'Barris Offee',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        assault: 'Jedi Assault Team (22 BBY)',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Survivor',
        tags: ["Mirialan", "Jedi Master", "Green", "Fall of the Jedi", "Reign of the Empire", "Jedi Assault Team", "Clone Wars", "Jedi General", "Order 66 Survivors"],
        movies: ["Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith", "Star Wars Rebels"]
    },
    {
        id: 32,
        imgSrc: 'images/jedi/BarrissOffee.webp',
        imgSrc2: 'images/jedi/Barris_Offee_Wallpaper.jpeg',
        name: 'Barriss Offee',
        homeworld: 'Mirial',
        species: 'Mirialan',
        gender: 'Female',
        masters: ["Luminara Unduli", "Darth Vader"],
        rank: 'Jedi Knight',
        ranks: 'Knight',
        lightsaber: 'blue',
        order66: 'Survivor',
        tags: ["Mirialan", "Jedi Knight", "Blue", "Fall of the Jedi", "Reign of the Empire", "Clone Wars", "Sith", "Order 66 Survivors"],
        movies: ["Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Tales of the Empire"]
    },
        {
        id: 33,
        imgSrc: 'images/jedi/Quinlan_Vos.webp',
        name: 'Quinlan Vos',
        homeworld: 'Kiffu',
        species: 'Kiffar',
        gender: 'Male',
        spouse: 'Asajj Ventress (lover)',
        masters: ["Tholme", "Asajj Ventress", "Dooku"],
        padawans: 'Aayla Secura',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'green',
        sith: 'Apprentice to Count Dooku',
        stark: '44 BBY',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Survivor',
        hidden: 'Hidden Path',
        tags: ["Kiffar", "Jedi Master", "Green", "Fall of the Jedi", "Reign of the Empire", "Stark Hyperspace War", "Clone Wars", "Jedi General", "Order 66 Survivors", "Hidden Path"],
        movies: ["Star Wars I: The Phantom Menace", "Star Wars: The Clone Wars", "Tales of the Underworld"]

    },
    {
        id: 34,
        imgSrc: 'images/jedi/AaylaSecura.webp',
        imgSrc2: 'images/jedi/Aayla_Secura_Wallpaper.jpeg',
        name: 'Aayla Secura',
        homeworld: 'Ryloth',
        birth: '48BBY, Ryloth',
        death: '19BBY, Felucia',
        species: "Twi'lek",
        gender: 'Female',
        masters: 'Quinlan Vos',
        padawans: 'Tutso Mara',
        rank: 'Jedi Master',
        ranks: 'Master',
        lightsaber: 'blue',
        midochlorians: '10,000',
        assault: '22 BBY',
        clone: 'Jedi General (22-19 BBY)',
        order66: 'Victim',
        tags: ["Twi'lek", "Blue", "Jedi Master", "Fall of the Jedi",  "Clone Wars", "Jedi General", "Jedi Assault Team", "Order 66 Victims"],
        movies: ["Star Wars II: Attack of the Clones", "Star Wars: The Clone Wars", "Star Wars III: Revenge of the Sith"]    
    }
];

export function addJedi(character) {
    jedi.push(character);
}