export const mandalorians =  [
    {
        id: 1,
        imgSrc: 'images/mandalorians/Jango_Fett.webp',
        name: 'Jango Fett',
        homeworld: 'Concord Dawn',
        birth: '66 BBY',
        death: '22 BBY, Genosis',
        species: 'Human',
        gender: 'Male',
        children: ["Boba Fett", "Omega"],
        apprentices: ["Cad Bane", "Boba Fett"],
        clans: 'Clan Fett',
        groups: ["Bounty Hunters' Guild", "Confederacy of Independent Systems"],
        weapons: 'WESTAR-34 Blaster Pistols',
        tags: ["Human", "Clan Fett", "Bounter Hunter Guild", "Confederacy of Independent Systems"]
    },
    {
        id: 2,
        imgSrc: 'images/mandalorians/BobaFett-SWI206.webp',
        name: 'Boba Fett',
        homeworld: 'Kamino',
        birth: '32 BBY, Kamino',
        species: 'Human',
        gender: 'Male',
        parents: 'Jango Fett',
        siblings: 'Omega',
        masters: ["Jango Fett", "Aurra Sing", "Bossk", "Cad Bane", "Tusken Warrior"],
        apprentices: ["Drash", "Skad"],
        clans: 'Clan Fett',
        groups: ["Aurra Sing's Crew", "Krayt's Claw", "Nakano Lash's Crew", "Jabba's Criminal Empire", "T'onga's Crew", "Fett Gotra"],
        weapons: 'EE-3 Carbine Rifle',
        tags: ["Human", "Clan Fett", "Aurra Sing's Crew", "Krayt's Claw", "Nakano Lash's Crew", "Jabba's Criminal Empire", "Bounty Hunters' Guild", "T'onga's Crew", "Fett Gotra"]
    },
    {
        id: 3,
        imgSrc: 'images/mandalorians/DinDjarin.webp',
        name: 'Din Djarin',
        homeworld: ["Aq Vetina", "Concordia"],
        birth: 'Prior to 19 BBY',
        species: 'Human',
        gender: 'Male',
        children: 'Din Grogu',
        clans: ["Clan Mudhorn", "The Tribe"],
        groups: ["Death Watch", "Children of the Watch", "Bounty Hunters' Guild", "Ranzar Malk's Crew", "Fett Gotra", "New Republic"],
        weapons: ["Relby-v10 Grenade Launcher", "EE-3 Carbine Rifle", "DL-21 Blaster Pistol", "Drum Blaster"],
        tags: ["Human", "Clan Mudhorn", "Death Watch", "The Tribe", "Children of the Watch", "Bounty Hunter's Guild", "Ranzar Malk's Crew", "Fett Gotra", "New Republic"]
    },
    {
        id: 4,
        imgSrc: 'images/mandalorians/TheArmorer.webp',
        name: 'The Armorer',
        homeworld: 'Mandalore',
        species: 'Human',
        gender: 'Female',
        clans: 'The Tribe',
        groups: 'Children of the Watch',
        tags: ["Human", "The Tribe", "Children of the Watch"],
    },
    {
        id: 5,
        imgSrc: 'images/mandalorians/BoKatan.webp',
        name: 'Bo-Katan Kryze',
        homeworld: ["Kalevala", "Mandalore"],
        species: 'Human',
        gender: 'Female',
        parents: 'Adonai Kryze',
        siblings: 'Satine Kryze',
        clans: ["Clan Kryze", "The Tribe"],
        groups: ["Death Watch", "Shadow Collective", "Mandalore Resistance", "Mandalorian Resistance", "Bo-Katan Kryze's Unit", "Children of the Watch"],
        weapons: ["Darksaber", "Dual WESTAR-35 Blaster Pistols", "Wrist Blaster", "Electroshock Darts", "Wrist Vibroblade", " Whipcord Launcher", "Shield Projector"], 
        tags: ["Human", "Clan Kryze", "Death Watch", "Nite Owls", "Shadow Collective", "Mandalore Resistance", "Mandalorian Resistance", "Bo-Katan Kryze's Unit", "The Tribe", "Children of the Watch"]
    },
    {
        id: 6,
        imgSrc: 'images/jedi/Sabine_Wren.webp',
        name: 'Sabine Wren',
        homeworld: ["Krownest", "Mandalore"],
        birth: '21 BBY, Mandalore',
        species: 'Human',
        gender: 'Female',
        father: "Alrich Wren",
        mother: "Ursa Wren",
        siblings: 'Tristian Wren',
        clans: 'Clan Wren',
        groups: ["Galactic Empire", "Rebel Alliance", "Mandalorian Resistance", "New Republic"],
        weapons: ["Paired Blaster Barrels", "Flamethrower", "Shield Projector", "Paralyzing Darts"],
        tags: ["Human", "Clan Wren", "Galactic Empire", "Rebel Alliance", "Mandalorian Resistance", "Ghost Crew", "New Republic"]
    },
    {
        id: 7,
        imgSrc: 'images/mandalorians/Pre_Vizsla.jpg',
        name: 'Pre Vizsla',
        homeworld: 'Mandalore',
        death: '19 BBY, Mandalore',
        species: 'Human',
        gender: 'Male',
        clans: 'Clan Vizsla',
        groups: ["Death Watch", "New Mandalorians", "Shadow Collective"],
        weapons: ["Darksaber", "WESTAR-35 Blaster Pistols"],
        tags: ["Human", "Clan Vizsla", "Death Watch", "New Mandalorians", "Shadow Collective", "Confederacy of Independent Systems"]
    },
    {
        id: 8,
        imgSrc: 'images/mandalorians/PazVizsla.webp',
        name: 'Paz Vizsla',
        homeworld: 'Mandalore',
        death: '9 ABY, Mandalore',
        species: 'Human',
        gender: 'Male',
        children: 'Ragnar Vizsla',
        clans: ["Clan Vizsla", "The Tribe"],
        groups: 'Children of the Watch',
        weapons: ["M-55 Medium Repeating Blaster", "Vibro-Knife"],
        tags: ["Human", "Clan Vizsla", "The Tribe", "Children of the Watch" ]
    },
    {
        id: 9,
        imgSrc: 'images/mandalorians/KoskaReeves.webp',
        name: 'Koska Reeves',
        homeworld: 'Mandalore',
        species: 'Human',
        gender: 'Female',
        clans: 'Clan Kryze',
        groups: ["Mandlorian Resistance", "Nite Owls", "Bo-Katan Kryze's Unit"],
        weapons: ["WESTAR-35 Blaster Pistols", "Mandalorian Vambraces"],
        tags: ["Human", "Clan Kryze", "Mandalorian Resistance", "Nite Owls", "Bo-Katan Kryze's Unit"]
    },
    {
        id: 10,
        imgSrc: 'images/mandalorians/AxeWoves.webp',
        name: 'Axe Woves',
        homeworld: 'Mandalore',
        species: 'Human',
        gender: 'Male',
        clans: 'Clan Kryze',
        groups: ["Mandalorian Resistance", "Nite Owls", "Bo-Katan Kryze's Unit"],
        weapons: ["WESTAR-35 Blaster Pistol", "Vibro-Knife"],
        tags: ["Human", "Clan Kryze", "Mandalorian Resistance", "Nite Owls", "Bo-Katan Kryze's Unit"]
    },
    {
        id: 11,
        imgSrc: 'images/mandalorians/RookKast.webp',
        name: 'Rook Kast',
        homeworld: 'Mandalore',
        groups: ["Death Watch", "Shadow Collective"],
        rank: 'Mandalorian Super Commandos',
        weapons: ["WESTAR-35 Blaster Pistols"],
        tags: ["Human", "Death Watch", "Shadow Collective", "Mandalorian Super Commandos"]
    },
    {
        id: 12,
        imgSrc: 'images/mandalorians/Gar_Saxon-FA.webp',
        name: 'Gar Saxon',
        homeworld: 'Mandalore',
        death: '2 BBY, Krownest',
        species: 'Human',
        gender: 'Male',
        siblings: 'Tiber Saxon',
        clans: 'Clan Saxon',
        groups: ["Shadow Collective", "Galactic Empire"],
        rank: ["Mandalorian Super Commandos", "Imperial Super Commandos"],
        weapons: "Galar-90 File",
        tags: ["Human", " Clan Saxon", "Shadow Collective", "Mandalorian Super Commandos", "Galactic Empire", "Imperial Super Commandos"]
    },
    {
        id: 13,
        imgSrc: 'images/mandalorians/Tiber_Saxon.jpg',
        name: 'Tiber Saxon',
        homeworld: 'Mandalore',
        death: "1 BBY, Tiber Saxon's Star Destroyer, Mandalore",
        species: 'Human',
        gender: 'Male',
        siblings: 'Gar Saxon',
        clans: 'Clan Saxon',
        group: 'Galactic Empire',
        rank: 'Imperial Super Commandos',
        tags: ["Human", "Galactic Empire", "Imperial Super Commandos"]
    },
    {
        id: 14,
        imgSrc: 'images/mandalorians/TristanWren.webp',
        name: 'Tristan Wren',
        homeworld: 'Krownest',
        birth: 'After 21 BBY',
        death: 'Between 4-5 ABY, Mandalore',
        species: 'Human',
        gender: 'Male',
        father: 'Alrich Wren',
        mother: 'Ursa Wren',
        siblings: 'Sabine Wren',
        clans: 'Clan Wren',
        groups: ["Galactic Empire", "Mandalorian Resistance"], 
        rank: 'Imperial Super Commandos',
        weapons: 'WESTAR-35 Blaster Pistols',
        tags: ["Human", "Clan Wren", "Galactic Empire", "Imperial Super Commandos", "Mandalorian Resistance", "Night of a Thousand Tears"]
    },
    {
        id: 15,
        imgSrc: 'images/mandalorians/Alrich_Wren.jpg',
        name: 'Alrich Wren',
        homeworld: 'Krownest',
        death: 'Between 4-5 ABY, Mandalore',
        species: 'Human',
        gender: 'Male',
        spouse: 'Ursa Wren',
        children: ["Sabine Wren", "Tristan Wren"],
        clans: 'Clan Wren',
        groups: 'Mandalorian Resistance',
        tags: ["Human", "Clan Wren", "Mandalorian Resistance", "Night of a Thousand Tears"]
    },
    {
        id: 16,
        imgSrc: 'images/mandalorians/UrsaWren.webp',
        name: 'Ursa Wren',
        homeworld: 'Krownest',
        death: 'Between 4-5 ABY, Mandalore',
        species: 'Human',
        gender: 'Female',
        spouse: 'Alrich Wren',
        children: ["Sabine Wren", "Tristan Wren"],
        clans: 'Clan Wren',
        groups: ["Death Watch", "Mandalore Resistance", "Galactic Empire", "Mandalorian Resistance"],
        rank: 'Nite Owls', 
        weapons: [""],
        tags: ["Human", "Clan Wren", "Death Watch", "Siege of Mandalore", "Mandalore Resistance", "Nite Owls", "Galactic Empire", "Mandalorian Resistance", "Night of a Thousand Tears"]
    },
    {
        id: 17,
        imgSrc: 'images/mandalorians/FennRau.webp',
        name: 'Fenn Rau',
        homeworld: 'Concord Dawn',
        species: 'Human',
        gender: 'Male',
        clans: 'Clan Vizsla',
        groups: ["Mandalorian Protectors", "Skull Squadron", "Galactic Empire", "Phoenix Cell", "Clan Wren", "Mandalorian Resistance"],
        rank: ["Journeyman Protectors", "Skull Leader"],
        weapons: 'Dual WESTAR-35 Blaster Pistols',
        tags: ["Human", "Mandalorian Protectors", "Journeyman Protectors", "Skull Squadron", "Galactic Empire", "Phoenix Cell", "Mandalorian Resistance"]
    },
    {
        id: 18,
        imgSrc: 'images/mandalorians/Hark.jpg',
        name: 'Hark',
        species: 'Human',
        gender: 'Male',
        groups: 'Galactic Empire',
        rank: 'Imperial Super Commandos',
        tags: ["Human", "Galactic Empire", "Imperial Super Commandos"]
    },
    {
        id: 19,
        imgSrc: 'images/mandalorians/Kestu_Onyo.jpg',
        name: 'Kestu Onyo',
        homeworld: 'Shukut',
        birth: '23 BBY',
        species: 'Human',
        gender: 'Male',
        groups: ["Galactic Empire", "Imperial Academy", "Black Sun", "Xomit Transport Systems", "Phoenix Cell"],
        tags: ["Human", "Galactic Empire", "Imperial Academy", "Black Sun", "Xomit Transport Systems", "Phoenix Cell"]
    },
    {
        id: 20,
        imgSrc: 'images/mandalorians/Almec.jpg',
        name: 'Almec',
        homeworld: 'Mandalore',
        death: '19 BBY, Mandalore',
        species: 'Human',
        gender: 'Male',
        groups: ["New Mandalorians", "Mandalorian Government Council", "Shadow Collective"],
        weapons: "WESTAR-35 Blaster Pistols",
        tags: ["Human", "New Mandalorians", "Mandalorian Government Council", "Shadow Collective"]
    }
]